### DISCUSSION TITLE
Testing - it is possible to use Craft::$app object with codeception acceptance tests?

### DISCUSSION THREAD

**Discussion by piotrpog** [craftcms/cms#11616] [Q&A]
With Codeception unit tests, in order to use `Craft::$app` object in tests, i need to add `\craft\test\Craft` to `enabled` section of `unit.suite.yml`. Otherwise, this object returns `null`.

When i try to do the same with acceptance tests and `acceptance.suite.yml` and i try to run tests i get this error:

```
 PhpBrowser module conflicts with craft\test\Craft

  --
  This usually happens when you enable two modules with the same actions but with different backends.
  For instance, you can't run PhpBrowser, WebDriver, Laravel5 modules in one suite,
  as they implement similar methods but use different drivers to execute them.
  You can load a part of module (like: ORM) to avoid conflict.
```

When i remove `PhpBrowser` from enabled i dont get this error, but this module is needed for running tests.

How can this problem be solved?

**Comment by angrybrad** [comment]
Can you share your unit.suite.yml and acceptance.suite.yml and codeception configuration files?

**Comment by piotrpog** [comment]
acceptance.suite.yml:

```
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: 'http://localhost/test_codeception_4/web/'
        - \Helper\Acceptance         
step_decorators: ~        
```

unit.suite.yml

```
actor: UnitTester
modules:
    enabled:
        - Asserts
        - \Helper\Unit
        - \craft\test\Craft
    step_decorators: ~        
```

codeception.yml

```
actor: Tester
paths:
  tests: tests
  log: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
bootstrap: _bootstrap.php
params:
  - tests/.env
modules:
  config:
    \craft\test\Craft:
      configFile: "tests/_craft/config/test.php"
      entryUrl: "http://my-project.test/index.php"
      projectConfig: {}
      migrations: []
      plugins: []
      cleanup: true
      transaction: true
      dbSetup: { clean: false, setupCraft: false }
```
