### DISCUSSION TITLE
We should be able to limit users changing authors

### DISCUSSION THREAD

**Discussion by JayBox325** [craftcms/cms#16852] [Ideas]
I have a multi-site setup where each user owns a site and they shouldn't be able to do anything to see other site editors.

However, I notice that a user limited to a site can still edit their author field and assign it to another user not even associated with the current site. I have got around it for now using the CSS in the CP plugin, but it would be great to limit changing users for instances where a user can just create content and keep it to themselves.

![Uploading Screenshot 2025-03-07 at 19.41.49.png…]()

**Comment by JayBox325** [comment]
I have handled this for now using the CP CSS plugin and a module that adds `data-admin` to the body, where I need to:

- Remove the entry sidebar author field (maybe not needed?)
- Hide the ability to edit authors in the table view for entries

```css
body:not([data-admin="true"]) #authorIds-field {
  display: none !important;
}

body:not([data-admin="true"]) [data-attr="authors"] .chip-actions {
  display: none !important;
}
```

Alternatively, to just remove the actions chip to allow changing, I might go with this:

```css
body:not([data-admin="true"]) [data-attr="authors"] .chip-actions,
body:not([data-admin="true"]) #authorIds-field .chip-actions {
  display: none !important;
}
```

Because we have editors and authors of the posts, which may not be the admin user, the default Craft flow is confusing, plus, we're a multi-site platform, so the replacing author field would allow the author from Site A set an entry to be an author from Site B (where they have no permissions).

So, I've got a "bylines" channel (this is the industry term) where the author can choose who appears on the byline.

I think this would be a potentially common pattern across users of Craft.
