### DISCUSSION TITLE
Robust code

### DISCUSSION THREAD

**Discussion by szepeviktor** [craftcms/cms#8718] [Ideas]
Hello!

Please consider using @phpstan

On Level 0 it shows 5 issues, on Level max 3995
It is tricky to get started, described below in the NEON file.

`phpstan.neon.dist`

```yaml
# mkdir config storage
# ln -s ../.. vendor/craftcms/cms
# phpstan analyse -l 0

includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - src/
    autoload_files:
        # <?php define('CRAFT_VENDOR_PATH', dirname(__DIR__, 2).'/vendor/');
        - tests/static-analysis/bootstrap.php
        - vendor/twig/twig/src/Extension/CoreExtension.php
        - bootstrap/console.php
#        - bootstrap/web.php
    excludes_analyse:
        - src/test/
        - src/views/
```
