### DISCUSSION TITLE
Add "letterbox" image transform mode

### DISCUSSION THREAD

**Discussion by piotrpog** [craftcms/cms#8848] [Ideas] [answered]
Letterbox is a transform mode used in imager/imager-x plugin. It adds an empty area to top and bottom or left and right area of an image in order to fit it into specific dimensions.

Personally, I find it extremely useful, especially for things like product listings where each image needs to have same dimensions and images should not be cropped.

**Comment by brandonkelly** [comment]
Hm, this seems like it would be better handled with CSS that adds a background color to the image container or something, rather than adding additional pointless image data. I’ll leave it open though.

**Comment by CMeldgaard** [comment]
I dont think that the background color is the important thing with letterbox mode. I think the important part is that you can generete a grid of images, for instance for a webshop, where all images are the same dimensions.

**Reply by thupsi** [reply]
I suppose the newish CSS 'object-fit' property would be a good 'fit' (😜) in this case. But, like Brandon, I'm not certain that all the edge cases are covered with CSS, so I'm not opposed to the idea of a letterbox mode.

**Reply by brandonkelly** [reply]
> I think the important part is that you can generete a grid of images, for instance for a webshop, where all images are the same dimensions.

You could do that with either flexbox or grid these days.

**Reply by CMeldgaard** [reply]
Perhaps im missing something, but how would you maintain the same aspectratio of the image container ? for instance on a product grid, how would you make sure that the "image div" inside the "product div" has the same aspectratio across the entire grid with images thats not the aspectratio (because we can't crop the images).

**Reply by brandonkelly** [reply]
Let’s say you want each thumbnail to fit within a 300 x 200 container…

```twig
<div class="thumb-container">
  {{ asset.getImg({width: 300, height: 200, mode: 'fit'}, ['1x', '2x']) }}
</div>
```

And then in your CSS, using [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit):

```css
.thumb-container {
  width: 300px;
  height: 200px;
}
.thumb-container img {
  object-fit: contain;
}
```

Or using flexbox:

```css
.thumb-container {
  display: flex;
  width: 300px;
  height: 200px;
  justify-content: center;
  align-items: center;
}
```
