### ISSUE TITLE
Disabling auto-refresh on more than 1 section will not retain necessary changes to all sections in project config files

### ISSUE THREAD

**Issue by joepagan** [craftcms/cms#10160]
### Description

Disabling auto-refresh on more than 1 section will not retain necessary changes to all sections in project config files

state of `config/project/sections/photography--cad713ff-8485-4ab5-b6e8-df193c2e5937.yaml` after disabling auto-refresh on this particular section (what I wanted):

```
defaultPlacement: end
enableVersioning: true
handle: photography
name: Photography
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - ''
propagationMethod: all
siteSettings:
  62b01cf3-0997-446f-b44e-a4ceede4f311: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: services/_builder
    uriFormat: '{% if parent %}{parent.slug}/{% endif %}{slug}'
structure:
  maxLevels: 3
  uid: f864fced-109a-4c6d-8111-ad5e4a5c390b
type: structure
```

Same file after disabling auto-refresh in another section:

```
enableVersioning: true
handle: photography
name: Photography
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  62b01cf3-0997-446f-b44e-a4ceede4f311: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: services/_builder
    uriFormat: '{% if parent %}{parent.slug}/{% endif %}{slug}'
structure:
  maxLevels: 3
  uid: f864fced-109a-4c6d-8111-ad5e4a5c390b
type: structure
```

### Steps to reproduce

1. 2 sections have auto-refresh enabled
2. disable auto-refresh on section 1, suitable project config file changes occur
3. disable auto-refresh on a section 2, project config files reset section 1 (re-enabling auto-refresh for section 1 in project config files) so only section 2 now has auto-refresh disabled in the project config files
4. database retains changes (until project config is re-applied)

### Additional info

- Craft version: 3.7.11
- PHP version: 7.2
- Database driver & version:  mariadb:10.2.31
- Plugins & versions:
