### ISSUE TITLE
Control Panel Doesn't Load Properly on Non-standard Port

### ISSUE THREAD

**Issue by micchickenburger** [craftcms/cms#10687]
### Description

The control panel doesn't seem to load resources properly when running craft on non-standard ports.  The links all reference the correct port but resources like images, scripts, and stylesheets drop the port number.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/4521230/156854323-fb0b1e6d-9234-49fd-9c43-d0dc7165b233.png">

It just tries to load resources from `localhost` even though I configured the `BASE_CP_URL` to be `localhost:5000`.

#### docker-compose.yml
```yaml
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker-config/php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./craft:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      ENVIRONMENT: dev
      SECURITY_KEY: security_key
      DB_DSN: mysql:host=database;port=3306;dbname=craft
      DB_USER: user
      DB_PASSWORD: password
      DEFAULT_SITE_URL: http://localhost:5000
      BASE_CP_URL: http://localhost:5000

  database:
    build:
      context: .
      dockerfile: .docker-config/mysql/Dockerfile
    volumes:
      - ./craft/storage/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: craft
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8085:80
    environment:
      PMA_HOST: database

  nginx:
    build:
      context: .
      dockerfile: .docker-config/nginx/Dockerfile
    ports:
      - 5000:80
    volumes:
      - ./craft/web:/var/www/html/web
    depends_on:
      - app
```

#### config/general.php

```php
<?php
return [
  '*' => [
    // Control Panel access via environment variable
    'baseCpUrl' => craft\helpers\App::env('BASE_CP_URL') ?: null,

    // Control Panel trigger word
    'cpTrigger' => 'admin-login',
  ],
];
```

We do not use `.env` files.

### Steps to reproduce

1.  Use above configuration
2.  Navigate to control panel

### Additional info

- Craft version:  3.7.36
- PHP version:  8.1.3
- Database driver & version:  MySQL 8.0+
- Plugins & versions:  Will provide upon request
