### ISSUE TITLE
[4.0.0-beta.2] Elementsources in project.yaml are not respected when applying the project config

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#10774]
### Description

> Element source settings are now stored in the project config.

Exited about that, as it saves us from writing migrations.

However those settings are not (yet) respected when applying the project config against a fresh install: 
Also tried `craft project-config/apply --force`

This is in project.yaml

````
elementSources:
  craft\elements\Asset:
    -
      key: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      tableAttributes:
        - imageSize
        - dateModified
        - link
      type: native
    -
      heading: Internal
      type: heading
    -
      key: 'volume:3b60e4f9-36bb-4456-bee5-67160b5a3108' # User Photos
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
      type: native
    -
      key: 'volume:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temp Images
      type: native
  craft\elements\Entry:
    -
      key: '*'
      tableAttributes:
        - section
        - postDate
        - author
        - link
      type: native
    -
      key: singles
      type: native
    -
      key: 'section:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
      tableAttributes:
        - drafts
        - type
        - 'field:7df417e8-1eea-46d8-85a7-2a20370a881e' # Featured Image
        - postDate
        - author
        - link
      type: native
````

The element index still shows the default:

![image](https://user-images.githubusercontent.com/60010597/158798476-312f7340-c6d0-43ed-843b-e5b0ec51c978.png)

### Steps to reproduce

1. see above

### Additional info

- Craft version: 4.0.0-beta.2
- PHP version: 8.0.15
- Database driver & version:
- Plugins & versions: none
