### ISSUE TITLE
[3.x]: Support Codeception REST module

### ISSUE THREAD

**Issue by yoannisj** [craftcms/cms#12087]
### Description
I am trying to setup a Codeception test suite to test the [Element API](https://plugins.craftcms.com/element-api) endpoints of a Craft-CMS website. I followed the instructions in Craft's documentation to setup Codeception tests, and followed the Codeception guide to test APIs with the REST module, but ran into several incompatibility issues (described in the *Actual Behavior* section below).

### Steps to reproduce

1. Get a fresh Craft-CMS 3.7 installation
_I downloaded the zip file from the [Installation Instructions](https://craftcms.com/docs/3.x/installation.html#downloading-an-archive-file-manually) to get up and running inside a DDEV project._
2. Install Codeception ^4.1 with `composer require codeception/codeception:^4.1 --dev`
_Codeception ^3.1 is not compatible with PHP 8, and I did not manage to setup Craft-CMS tests with Codeception ^5.0._
3. Follow steps to [Setup Tests](https://craftcms.com/docs/3.x/testing/testing-craft/setup.html) for Craft-CMS from the documentation
_To run the example unit test  (steps 4-5), I had to comment out the `modules` setting in `config/app.php` (see #12088) and run `composer require codeception/module-yii2:^1.1 --dev` first_
4. Install the REST codception module with `composer require codeception/module-rest:^2.0 --dev`
5. Create a new suite for API tests with `php vendor/bin/codecept generate:suite api`
6. Create the API suite's required `_bootstrap.php` file with `cp tests/unit/_bootstrap.php tests/api/_bootstrap.php`
7. Enable the Craft and REST codeception modules in`tests/api.suite.yaml` like so:
```
actor: ApiTester
modules:
    enabled:
        - \craft\test\Craft
        - \Helper\Api
        - REST:
            depends: \craft\test\Craft
            part: JSON
            url: https://project-name.ddev.site
```
8. Install the Element API plugin via the Craft Plugin store.
9. Add an API endpoint in `config/element-api.php` to test against:
```
<?php
use craft\elements\Entry;

return [

    'endpoints' => [

        '/api/all-entries.json' => [
            'elementType' => Entry::class,
            'criteria' => [],
            'one' => false,
        ],

    ],

];
```
10. Create an example API test file `tests/api/ExampleCest.php` like so:
```
<?php
namespace yournamespace\tests\api;

class ExampleCest
{    
    public function testKnownEndpointReturnsJson( \ApiTester $I )
    {
        $I->send('get', '/api/all-entries.json');
        $I->seeResponseCodeIs(200);
        $I->seeResponseIsJson();
    }

    public function testUnknownEndpoint( \ApiTester $I )
    {
        $I->send('get', '/api/foo.json');
        $I->seeResponseCodeIs(404);
    }
}
```
11. Run example test with `php vendor/bin/codecept run api`

### Expected behavior

Both tests should pass.

I got there by adding the workarounds explained below, but they require a change to the Craft-CMS source code, and I believe they are not very robust or won't work for everyone anyway. 

### Actual behavior

- Throws `[yii\base\ErrorException] foreach() argument must be of type array|object, null given`

It seems like this is due the fact that –with the REST module enabled– Craft resolves URL rules with `craft\console\Request` component, but runs the tests with `craft\web\Request`. Therefore the `craft\web\UrlManager::rules` property is set to `null` when handling request made with `$I->send()` inside the tests.

In order to troubleshoot and dig deeper, I worked around this error by updating the [`craft\web\UrlManager ::__construct()`](https://github.com/craftcms/cms/blob/develop/src/web/UrlManager.php#L98) method as such:

```
    $config['rules'] = $this->_getRules() ?: [];
```

This resolves the error above, but also means that Craft does not recognize all web routes when running the tests (see below). I am guessing a better fix would be to resolve the URL rules with `craft\web\Request` instead.

- Throws `[ExternalUrlException] craft\test\Craft can't open external URL`

It looks like this is due to how the `$_SERVER['SERVER_PORT']` global falls back to `80` even if the `\craft\test\Craft` and module's `entryUrl` setting is set to an `https://` URL (see #).

I worked around this issue by including the `:443` port explicitly in `codeception.yaml > modules > config > \craft\test\Craft > entryUrl`.

- Does not find URL routes registered by modules and plugins

This is most probably related to the workaround for issue 1: the URL Rules get resolved to an empty array with `craft\console\Request`, which means the `UrlManager::EVENT_REGISTER_SITE_URL_RULES` and `UrlManager::EVENT_REGISTER_CP_URL_RULES` events don't get fired even when running tests with `craft\web\Request`.

I managed to workaround this issue by recreating the urlManager component before each request by setting `recreateApplication: false` and `recreateComponents: [ urlManager ]` in `codeception.yaml > modules > config > \craft\test\Craft`:

### Craft CMS version

3.7.55.3

### PHP version

8.0.21

### Operating system and version

Linux 5.10.124-linuxkit (DDEV v1.20.0)

### Database type and version

MySQL 10.4.25 (MariaDB 10.4)

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Element API 2.8.6.1
- codeception/codeception 4.2.2
- codeception/module-yii2 1.1.5
- codeception/module-rest 2.0.2
- codeception/module-asserts 1.3.1
- codeception/module-phpbrowser 1.0.3

**Comment by yoannisj** [comment]
@brianjhanson , ok so I kept fiddling with this and it turns out that the issues above are all due to the REST module's `url` setting alone. It looks like that `url` setting is what provokes the `craft\web\UrlManager::rules` to be resolved while the `request` component is still a `craft\console\Request`. All issues above would derivate from this, which makes sense AFAIK.

Indeed if I remove the `url` setting in the tests run and succeed without any of the workarounds:

**tests/api.suite.yaml**
```
actor: ApiTester
modules:
    enabled:
        - \craft\test\Craft
        - \Helper\Api
        - REST:
            depends: \craft\test\Craft
            part: JSON
```

**codeception.yaml**
```
actor: Tester
paths:
  tests: tests
  log: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
bootstrap: _bootstrap.php
params:
  - tests/.env
modules:
  config:
    \craft\test\Craft:
      configFile: "tests/_craft/config/test.php"
      entryUrl: "https://craft3-test.ddev.site/index.php"
      dbSetup:
        clean: false
        setupCraft: false
        applyMigrations: false
      projectConfig:
        folder: "config/project"
        reset: false
      migrations: []
      plugins: []
      cleanup: true
      transaction: true
```

`php vendor/bin/codecept run api` => ✅ so I think this ticket can safely be closed.

---

I spent a lot of time trying to understand why I was seeing these errors, and trying to get my api tests to run locally, so I would say it's worth adding a note the in the [Testing Craft](https://craftcms.com/docs/4.x/testing/testing-craft/testing-tips.html) docs for whoever is trying to add the codeception REST module –saying it's `url` setting should be omitted because it is incompatible. Unless the issue is deeper of course.

I am also wondering if it would not be best to make `$_SERVER['SERVER_PORT']` default to `443` when it the `entryUrl` setting uses `https://`. This might prevent issues in other testing scenarios, and seems relatively straight forward to do [here](https://github.com/craftcms/cms/blob/1039431af41c349e70e0e64824716883f7077f17/src/test/Craft.php#L715)
