### ISSUE TITLE
[4.x]: Creating/saving section: Getting unknown property: craft\events\SectionEvent::element

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#14528]
### Description

When saving an existing or creating a new `single` type section, an exception occurs on save:

```
Unknown Property – [yii\base\UnknownPropertyException](https://www.yiiframework.com/doc-2.0/yii-base-unknownpropertyexception.html)
Getting unknown property: craft\events\SectionEvent::element
```

![Screen shot 2024-03-05 um 12 13 41](https://github.com/craftcms/cms/assets/529443/f9d81fbf-faaf-42b9-94cc-850236b0a066)

### Steps to reproduce

1. Create or edit a section that is type `single`: 
![Screen shot 2024-03-05 um 12 13 28](https://github.com/craftcms/cms/assets/529443/afdc1b92-c0b1-4399-9cc6-a9b178b05867)
2. Enter any values or use empty values.
3. Save

Saving an existing type with this YAML settings will cause the exception as well:

```yml
defaultPlacement: end
enableVersioning: true
handle: adminSettings
name: 'Admin Settings'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0f9c8122-f788-42eb-863a-2eb5a20b804c: # $SYSTEM_NAME
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
type: single
```

### Expected behavior

Saving the section would show me an success message and the created section.

### Actual behavior

An exception occurs and the section would not be saved.

### Craft CMS version

4.7.4

### PHP version

8.2.16

### Operating system and version

Linux 6.6.12-linuxkit

### Database type and version

MySQL 5.7.42 / MySQL 8.0.36

### Image driver and version

Imagick 3.7.0

### Installed plugins and versions

- "craftcms/redactor": "3.0.4",
- "graylog2/gelf-php": "^1.7",
- "hillholliday/craft-user-manual": "^4.0.0",
- "monolog/monolog": "^2.6",
- "nystudio107/craft-minify": "4.0.1",
- "nystudio107/craft-seomatic": "4.0.40",
- "percipioglobal/craft-colour-swatches": "4.3.0",
- "renoki-co/php-k8s": "^3.5",
- "samdark/yii2-psr-log-target": "^1.1",
- "sebastianlenz/linkfield": "2.1.5",
- "simplygoodwork/craft-donkeytail": "3.0.1",
- "spicyweb/craft-neo": "4.0.5",
- "verbb/navigation": "2.0.25",
- "verbb/super-table": "3.0.12",
- "vlucas/phpdotenv": "^5.4.0",
- "yiisoft/yii2-redis": "^2.0"
