### ISSUE TITLE
[5.x]: Asset icons not showing in Safari

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#14833]
### Description

Icons for folders and non-image files don’t show in Safari. Found out that following css fixes it.

```css
.chip > .thumb svg { width: 100% }
```

### Craft CMS version

5.0.4

### Installed plugins and versions

- n/a
