### ISSUE TITLE
[5.x]: Assets UI Blank Headings Created when Temporary Uploads is Disabled

### ISSUE THREAD

**Issue by vanburenx** [craftcms/cms#15386]
### Description

If **Temporary Uploads** is disabled within the Assets UI setting when adding additional volumes a blank heading is created. This happens with each subsequent volume that's added and if you use the **Project Config** for a deployment etc. this behavior carries over even if you disabled **Temporary Uploads** (again) prior to using the **Project Config**.

### Steps to reproduce

1. add a volume
2. disable Temporary Uploads
3. add a new volume

### Expected behavior

The new volume is added without any blank headings appearing in the cp or reenabling Temporary Uploads.

### Actual behavior

If **Temporary Uploads** is disabled when creating new volumes, a blank heading is added to the Assets UI each time, and this also appears to influence the Project Config when using it to deploy/install.

---

I did find this issue https://github.com/craftcms/cms/issues/12840 related to source headings from last year just as an fyi. I also tested this with MySQL and on Craft v4 with the same results.

If a DB copy or any files are needed just let me know.

---

### Examples

Normal behavior if Temporary Uploads is enabled when added a new volume.

![1 0-pre](https://github.com/user-attachments/assets/f4903aba-838f-4d98-b582-60a0dcf42da8)
![1 1-pre](https://github.com/user-attachments/assets/d46fcbfd-ef02-4ff5-9896-d69fda56deda)

Behavior after Temporary Uploads is disabled when adding a new volume.

![1 2-post](https://github.com/user-attachments/assets/a917e466-673b-4169-b0d8-8bd5199b85c8)
![1 3-post](https://github.com/user-attachments/assets/57031114-2380-4f90-a62e-f9e27a8f9794)

Behavior after Temporary Uploads is again disabled prior to using Project Config to deploy/install.
- Pre deploy/install Assets UI
![2 0-pre-deploy](https://github.com/user-attachments/assets/618c65dd-af6b-479b-9efd-8b172b635372)
![2 1-deploy](https://github.com/user-attachments/assets/7d9a0999-064f-40c5-9245-f3f6a9ab2f02)
- Post deploy/install Assets UI
![2 2-deploy](https://github.com/user-attachments/assets/06249681-5e95-4747-831d-011487d61d1e)
![2 3-deploy](https://github.com/user-attachments/assets/d2951459-6a15-49ec-a132-9aa626551d4e)

### Craft CMS version

5.2.8

### PHP version

8.2.20

### Operating system and version

Linux 6.5.0-44-generic

### Database type and version

PostgreSQL 16.1

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- NA/None

**Comment by brandonkelly** [comment]
This is just the behavior any time a new native source is added, if you’ve already customized the sources for that element type. Same thing happens with entries, etc. Craft doesn’t know how you’d want to position it, so it adds a blank heading and lumps the new source after that.

**Comment by vanburenx** [comment]
Ok i get that when adding a source but is this the expected behavior once you're set and you use the project config to install or what am i missing here. Thanks.

**Comment by brandonkelly** [comment]
If `config/project/project.yaml` contains an `elementSources` key with a `craft\elements\Asset` nested key (where customized source settings are stored), then yes it’s expected.

**Comment by vanburenx** [comment]
Got it. So even with Temp Uploads set to `disabled: true` it's still going to be enabled and add a blank heading on setup. Thanks for taking the time to explain this I do appreciate it.

```
elementSources:
  craft\elements\Asset:
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:09e56dc9-e784-4a0d-983b-733e8103c7c0' # Volume One
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:dcc3b4d8-16d4-45c3-9bc9-a0263cd0bed7' # Volume Two
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:1f01eab2-3475-4642-a3a7-3178ecad2eb2' # Volume Three
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: true
      key: 'folder:33ec0443-0a30-4365-a0b0-569c5ca42c8d'
      tableAttributes:
        - filename
        - size
        - dateModified
        - link
      type: native
```
