### ISSUE TITLE
[5.x]: Temporary Uploads does not respect the element index config

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#15436]
### Description

We're seeing an issue where the _Temporary Uploads_ volume does not respect the settings in the project config.

We have moved the _Temporary Uploads_ volume next to the asset volume that we use for CMS uploads. This is what it looks like in a development environment:

![Screenshot 2024-07-29 at 12 29 37](https://github.com/user-attachments/assets/2ed86a97-93a1-464c-bdbe-9c177c39ab48)

`Uploads` is a volume using a local filesystem, `Temporary Uploads` is the native volume (which is still using the fallback behavior with a local filesystem). The other two sources are custom sources.

In the production environment, the _Temporary Uploads_ is instead displayed at the end, separated by an empty heading:

![Screenshot 2024-07-29 at 12 29 52](https://github.com/user-attachments/assets/3c71b5c1-9fd7-4ff5-855c-fbfb04a64000)

Running `project-config/apply --force` has no effect.

I can see that the order is correct in `config/project/project.yaml`, but this doesn't seem to have any effect:

```yaml
elementSources:
  craft\elements\Asset:
    -
      heading: Verzeichnisse
      type: heading
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:197b6543-0c1d-419f-95e7-f40c69ab130e' # Uploads
      tableAttributes:
        - size
        - imageSize
        - filename
        - dateCreated
        - link
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'folder:1830d024-2217-453a-a8a0-b6650991efe8'
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
      type: native
    -
      heading: Ansichten
      type: heading
    -
      condition:
        class: craft\elements\conditions\assets\AssetCondition
        conditionRules:
          -
            class: craft\elements\conditions\assets\FileTypeConditionRule
            operator: in
            uid: 4c2ed80b-db5e-4ca1-b0c4-7e818c3b1bcd
            values:
              - image
        elementType: craft\elements\Asset
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:e644e699-01ad-4b0d-a4cd-693bc1490ee6'
      label: Bild-Metadaten
      tableAttributes:
        - alt
        - 'field:f8cbb87f-0b10-426b-99bd-c94fa399a632' # Bildunterschrift
        - 'field:80fbf9c2-28b4-4640-8165-cb426d2d1381' # Bildnachweis
        - 'field:1af1f1eb-97de-44f9-beeb-79310654143f' # Bildnachweis-URL
      type: custom
    -
      condition:
        class: craft\elements\conditions\assets\AssetCondition
        conditionRules:
          -
            class: craft\elements\conditions\assets\FileTypeConditionRule
            operator: in
            uid: 503d78b6-73b8-4c1f-859c-2f6cfbd58e0c
            values:
              - image
          -
            class: craft\elements\conditions\assets\HasAltConditionRule
            uid: 72817ddc-e4bb-4562-911d-39c93b2003aa
            value: false
        elementType: craft\elements\Asset
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:e19c504a-a61e-4842-9a65-9470a498170c'
      label: 'Fehlender ALT-Text'
      tableAttributes:
        - alt
        - dateCreated
        - uploader
        - link
      type: custom
```

### Steps to reproduce

1. Move the Temporary Uploads volume to a different position.
2. Apply the config in a production environment.

### Craft CMS version

5.2.8

### PHP version

8.3

### Installed plugins and versions

-
