### ISSUE TITLE
[5.x]: Details misaligned on edit element pages without meta fields

### ISSUE THREAD

**Issue by ryansupercool** [craftcms/cms#16061]
### Description

When an element edit page doesn't have meta fields such as a matrix entry, the status field is misaligned.

![Image](https://github.com/user-attachments/assets/39d0daec-53f8-40c5-a803-104651e56de0)

This can be fixed with:

```css
.details > fieldset:first-child {
    margin-block-start: 0 !important;
}
```

### Steps to reproduce

1. Create an Matrix field that has an entry type without a slug field but with a status field.

### Expected behavior

Status field is aligned to the top of `#content`.

### Actual behavior

Status field is misaligned.

### Craft CMS version

5.5

### Installed plugins and versions

-
