### ISSUE TITLE
[5.x]: Cannot copy billing or shipping address on order edit screen

### ISSUE THREAD

**Issue by philipboomy** [craftcms/cms#16763]
### Description

It would be nice to be able to copy the address on the order edit screen. We some times reply to customers where we list their address for confirmation. We cannot copy paste the address anymore. We have to click the edit of the address and then copy paste 1 input field at a time. I am not sure if this is a setting change or on purpose.

**Comment by nfourtythree** [comment]
Hi @philipboomy 

Thank you for your message.

Commerce implements the address card preview as dictated by Craft itself. So for this we will need a figure out a solution that works in the core of Craft (you can see the same behaviour if you look at addresses on a user).

Will transfer this issue across to the Craft repo so we can track any progress.

If you urgently require a solution for you could add the following code in a custom module's `init()` method. 

```php
if (Craft::$app->getRequest()->getIsCpRequest()) {
    Craft::$app->getView()->registerCss('.order-address-display .card { -webkit-user-select: initial; -moz-user-select: initial; -ms-user-select: initial; user-select: initial; }');
}
```

Thanks!

**Comment by brandonkelly** [comment]
Related: #16632

**Comment by boboldehampsink** [comment]
I added this custom CSS via @nfourtythree's suggestion so that the card's contents are selectable but not firing the click event to open the drawer, but the title and button still do:

```css
#orderDetailsTab div[model-name="billing"] {
  pointer-events: none;
}

#orderDetailsTab div[model-name="billing"] button,
#orderDetailsTab div[model-name="billing"] a {
  pointer-events: auto;
}

.order-address-display .card {
  user-select: auto !important;
}
```
