### ISSUE TITLE
Styling: overflow auto causes outside field elements to appear behind sidebar

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#2313]
### Description

I am working on a plugin for the Froala WYSIWYG editor integration in Craft v3. Almost done.
The editor has a feature called "quick insert" which is cool to insert content when you're in the middle of the page.

The Quick insert tool is appearing on the left side of the editor. But it is showing behind the sidebar since the CSS has an `overflow-y: auto;` online

See
![image](https://user-images.githubusercontent.com/398492/35008548-2c218686-fafd-11e7-88e8-c58159fc7d0b.png)

```css
#main-container #main #main-content #sidebar,
#main-container #main #main-content #content-container,
#main-container #main #main-content #details {
    overflow-y: auto;
}
```

When I change this to `visibile`, everything works fine.

```css
#main-container #main #main-content #sidebar,
#main-container #main #main-content #content-container,
#main-container #main #main-content #details {
    overflow-y: visible;
}
```

### Steps to reproduce

1. Download plugin from https://github.com/froala/Craft-Froala-WYSIWYG/tree/v3
2. Install the plugin
3. Add a field as Froala WYSIWYG
4. Add the field to a section
5. Edit a page from the section
6. Click in the editor field to see the quick insert tool

### Additional info

- Craft version: Craft Pro 3.0.0-RC5
- PHP version: 7.1.12
- Database driver & version: MySQL 5.7.20
- Plugins & versions: Froala WYSIWYG (v3 dev as per above link)
