### ISSUE TITLE
3.1 - Enabling Project Config prints volume .env variables to project.yaml

### ISSUE THREAD

**Issue by michaelroper** [craftcms/cms#3531]
### Description
I am using .env variables to set the S3 settings for my asset volumes in `config/volumes.php` ([as shown here](https://github.com/craftcms/aws-s3)):
```php
return [
    '*' => [
        'images' => [
            'hasUrls' => true,
            'url' => getenv('S3_URL'),
            'keyId' => getenv('AWS_API_KEY'),
            'secret' => getenv('AWS_SECRET'),
            'bucket' => getenv('S3_BUCKET'),
            'subfolder' => getenv('S3_SUBFOLDER') . 'images',
            'region' => getenv('S3_REGION'),
            'expires' => getenv('S3_EXPIRES'),
            'cfDistributionId' => getenv('S3_CLOUDFRONT'),
        ],
    ],
];
```

When I enabled the `useProjectConfigFile` option, it created the `config/project.yaml` file, and printed the _values_ of my .env variables into the Volumes settings, like below:
```yaml
volumes:
  dd3dd1a2-3a7e-4759-91d0-e055c09f5713:
    handle: images
    hasUrls: true
    name: Images
    settings:
      bucket: files.foo.com
      cfDistributionId: ABDCEFG
      expires: '5 days'
      keyId: ABCDEFGGGGGGGG
      region: ap-southeast-2
      secret: A+1234567895555555555
      storageClass: ''
      subfolder: www/images
    sortOrder: '4'
    type: craft\awss3\Volume
    url: 'https://files.foo.com/'
```
Obviously, this isn't ideal, because I'd used .env variables there to specifically keep them out of files in the repo, and if I am supposed to commit the `project.yaml` to my repo, it kind of defeats the purpose if those variables are in there.

I know that I can set the *Base URL* value to `$S3_URL` when in the CP; if I do that, the `project.yaml` will pass that through as `url: $S3_URL`, but will still print the overriding variables. 

Inversely, if I try to modify the values in the `project.yaml` file and put the .env vars in like below, it will break when I try to load the CP.
```yaml
volumes:
  dd3dd1a2-3a7e-4759-91d0-e055c09f5713:
    handle: images
    hasUrls: true
    name: Images
    settings:
      bucket: $S3_BUCKET
      cfDistributionId: $S3_CLOUDFRONT
      expires: $S3_EXPIRES
      keyId: $AWS_API_KEY
      region: $S3_REGION
      secret: $AWS_SECRET
      storageClass: ''
      subfolder: www/images
    sortOrder: '4'
    type: craft\awss3\Volume
    url: $S3_URL
```
That outputs like the below in the settings page, but doesn't work when i try to access the Assets section.
![image](https://user-images.githubusercontent.com/60287/49569581-4ccd2900-f96f-11e8-9a9d-40146e8228cf.png)

Is this (un)expected behaviour until all plugins can support the special Environment Variables/Aliases field type for settings?

### Additional info

- Craft version:  3.1.0-beta.4
- PHP version: 7.2
