### ISSUE TITLE
[Feature Request] yaml translation files

### ISSUE THREAD

**Issue by Moskydesign** [craftcms/cms#3550]
I was wondering if it would't be possible to allow translation files for static messages to be created as yaml file in stead of the php files now.

They have the advantage to be more user friendly. Translators can read them better and don't have to worry about syntax, escaping characters, etc.

And they allow for nesting strings, this would make namespacing easier for example. On bigger sites with lots of strings to be translated providing some structure is a big plus.

Implementing this doesn't have to require a lot of changes I think, only adding a yaml parser that will convert the file contents to a php array similar to the one that you currently have to create manually.

**Comment by Moskydesign** [comment]
With translations context can be very important to be able to make a proper translation.
A single word in English can have multiple translations in an other language depending on the context of where it is used.

To make sure one translation doesn't change other strings in a different context its good practice to use abstract keys in stead of plain strings.
For example, a contact form submit button can have the value "Send", but to in stead we use the key "contact-form.submit.value". In the translation file this will then be converted to "Send" in English, "Verzenden" in Dutch and so on.

A little background to come to the point why nesting is useful.
In a yaml file you can do something like this:

```
contact-form:
   email:
      label: "E-mail address"
      placeholder: "Your e-mail address"
   subject:
      label: "Subject"
      placeholder: "What do you wanne talk about"
   submit:
      value: "Send"
```

So you can group together the keys based on context.
On larger projects with lots of strings to translate this method also provides some structure.

I have a history in working with Symfony where this is way of working is frequently used.
