### ISSUE TITLE
Invalid transform handle exception after update from 3.0.37 to 3.1.1

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#3649]
### Description

Updating from 3.0.37 to 3.1.1 causes error in front-end:

```
Asset Transform Error – craft\errors\AssetTransformException
Invalid transform handle: maxfitXLarge
```

`maxfitLarge` exists in project.yml and asset transforms settings:

```
fe9a8bf0-3b13-4476-8fad-ca6ccfd3293e:
    format: jpg
    handle: maxfitXlarge
    height: ''
    interlace: none
    mode: fit
    name: 'Max Fit – Xlarge'
    position: center-center
    quality: '60'
    width: '2500'
```
Even changing to `height: null` won't fix it.

I migrated with `./craft migrate/all` (successfully) after the composer update.
