### ISSUE TITLE
Project config values changing between strings and boolean values in different environments

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#3695]
### Description
I've updated a project to the latest version of Craft and enabled project config control. When I make changes locally I'm seeing values such as...
```yml
siteSettings:
  215a576d-d6b9-41cf-bff5-d7306aa1d646:
    hasUrls: '1'
```

But when I apply this config to our staging environment these are changed to 
```yml
siteSettings:
  215a576d-d6b9-41cf-bff5-d7306aa1d646:
    hasUrls: true
```

Because this change occurs I'm unable to set `"allowAdminChanges" => false` as I receive an error saying changes to the project config are "read-only".

### Additional info

- Craft version: 3.1.3
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.24
- Plugins & versions:
