### ISSUE TITLE
Add warning header to project.yaml file to indicate it should not be edited directly?

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#3800]
### Description
Should there be a comment at the top of `project.yaml` to deter developers from editing it directly? In many (if not all cases) `project.yaml` works off of modified dates, UUIDs, etc. A simple header might prevent people from attempting to edit values outside of the control panel:

```yaml
# WARNING!
# THIS FILE SHOULD NOT BE EDITED DIRECTLY

categoryGroups:
  912d738d-e72f-44a3-a69e-7c24617b7b98:
    handle: example
    name: Example
    siteSettings:
```

### Additional info

- Craft version: Craft Pro 3.1.8
- PHP version: 7.2.12
- Database driver & version: MySQL 5.7.24
