### ISSUE TITLE
project-config creates project.yaml that doesn't sync

### ISSUE THREAD

**Issue by marionnewlevant** [craftcms/cms#4288]
### Description
Newly generated project.yaml fails to sync, complains about being created for a different version of Craft.

### Steps to reproduce

1. New Craft install v 3.1.27
2. Set `'useProjectConfigFile' => true` in general.php
3. Run ./craft project-config/sync
4. Error:
> Your `project.yaml` file was created for different versions of Craft and/or plugins than what’s currently installed. Try running `composer install` from your terminal to resolve.

`composer install` finds nothing to install.

### Additional info

- Craft version: 3.1.27
- PHP version: 7.0.13
- Database driver & version: MySQL 5.7.16
- Plugins & versions: none

This is what is in my `project.yaml`
```
email:
  fromEmail: marion.newlevant@gmail.com
  fromName: bareCraft
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  1aed1b28-9411-4f7d-b18d-b65545d7d29e:
    name: Common
siteGroups:
  6345086c-14bf-49b4-ad9b-408ed8bdb9e5:
    name: bareCraft
sites:
  2bde174e-c379-4fb0-a529-a50f128a49fb:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: bareCraft
    primary: true
    siteGroup: 6345086c-14bf-49b4-ad9b-408ed8bdb9e5
    sortOrder: 1
system:
  edition: solo
  name: bareCraft
  live: true
  schemaVersion: 3.1.28
  timeZone: America/Los_Angeles
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
```
