### ISSUE TITLE
Volume fields not syncing from project.yaml

### ISSUE THREAD

**Issue by erktime** [craftcms/cms#4345]
### Description
Volume fields are not being syncronized from the `project.yaml` file. 

### Steps to reproduce

1. Have a `project.yaml` file with with a defined volume that has fields defined. Example:

```yaml
volumes:
  55522029-46df-4733-a6e3-fa3cd00a5ec8:
    name: Assets
    handle: assets
    type: craft\awss3\Volume
    hasUrls: true
    url: $AWS_S3_URL
    settings:
      subfolder: $AWS_S3_SUBFOLDER
      keyId: $AWS_S3_KEY
      secret: $AWS_S3_SECRET
      bucketSelectionMode: manual
      bucket: $AWS_S3_BUCKET
      region: $AWS_S3_REGION
      expires: ''
      makeUploadsPublic: ''
      storageClass: ''
      cfDistributionId: ''
      cfPrefix: ''
      autoFocalPoint: ''
    sortOrder: 1
    fieldLayouts:
      eda2ba58-cdde-413a-a365-676067b06b1f:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              a8cceb77-fd3b-4e04-8fbd-bc7a6b4ec92c:
                required: false
                sortOrder: 1
              86483d73-d56f-46c3-84de-c4f32613b37b:
                required: false
                sortOrder: 2
              afb31480-24ba-45c0-9c94-ef94ae865cf0:
                required: false
                sortOrder: 3
              6e0530cb-cae0-4bf3-96f0-a16064314f75:
                required: false
                sortOrder: 4
```

2. Re-install craft (or get altered project.yaml file from other env) and allow the system config to be restored from the `project.yaml`.
3. Notice that the volume was correctly created, but it will not have any fields associated with it.

### Additional info

- Craft version: 3.1.28
- PHP version: 7.3.4
- Database driver & version: mysql 5.7
- Plugins & versions:  Amazon S3 (1.2.2) && Redactor (2.3.3.2)
