### ISSUE TITLE
GitLab runner build using composer won't succeed

### ISSUE THREAD

**Issue by gbowne-quickbase** [craftcms/cms#4599]
### Description
I'm running my project in GitLab and and deploying to AWS and this has worked well for us throughout the Craft 2 lifecycle. Essentially, the backend build does the `composer install`, a front end build does the `npm install` and `webpack`, and the whole thing is deployed to servers.

We've run into a problem where plugin installation works fine on local machines through `composer install` (running version 1.8.4 or 1.8.6) but the gitlab runner does not. Every time, we get an error like 

```    
...[all the other installs here]                                                                           
Extracting archive  - Installing composer/composer (1.6.3): Downloading (100%)
 Extracting archive

  [RuntimeException]
  craft/plugins/deleteentryversions/ does not exist and could not be created.  
```                                                                               

I searched through my project and found a file in the `composer/installers` vendor directory called 'CraftInstaller.php' [https://github.com/composer/installers/blob/master/src/Composer/Installers/CraftInstaller.php] that sets the file path for plugins to `craft/plugins/{$name}` so we think this is being invoked by composer required by somewhere in the chain, and we fail. The `composer/installers1 doesn't seem to be referenced in the `composer.lock` file at all.

Here's the excerpt from our `.gitlab-ci.yaml` file that does the back end build
```
build_backend:
  image: composer:1.8.6
  script:
    - composer install -v --prefer-dist --no-dev --no-interaction --optimize-autoloader
  cache:
    key: composer
    paths:
      - vendor/
  artifacts:
    paths:
      - vendor/
    expire_in: 2 mos
  stage: build
  only:
    - branches
  tags:
    - aws
```

### Steps to reproduce

1. Install GitLab Runner (for osX https://gitlab.com/gitlab-org/gitlab-runner/blob/master/docs/install/osx.md) and Docker, add your project directory to your docker instance 
2. Run gitlab-runner exec docker build_backend

### Additional info

- Craft version: 3.2 & 3.1.34
- PHP version: 7.1.30
- Database driver & version: MySQL Ver 14.14 Distrib 5.7.26, for osx10.14
- Plugins & versions: 
[composer.json.txt](https://github.com/craftcms/cms/files/3403609/composer.json.txt)
