### ISSUE TITLE
`project-config/rebuild` removes entry types that don't have a field layout since 3.1.34

### ISSUE THREAD

**Issue by benface** [craftcms/cms#4600]
After updating to Craft CMS 3.1.34 (from 3.1.32.1), I ran `./craft project-config/rebuild` since I saw in the release notes for 3.2 that "if you’ve ever run the `project-config/rebuild` command [and I have], it’s highly recommended that you run it again with Craft 3.1.34, before updating to Craft 3.2." I looked at the changes to `project.yaml` quickly and everything looked good, so I pushed to production, synced the changes, and... some sections ended up losing all their entries. I looked at the changes to `project.yaml` more carefully and it seems that the rebuild command removed all the entry types that didn't have a field layout, which in turn deleted entries belonging to that entry type. Here's an example:

Before running the rebuild command:

```
  7d79c3ca-57d0-4828-ac16-0798f5e81770:
    name: 'Categories'
    handle: categories
    type: structure
    enableVersioning: true
    propagateEntries: true
    siteSettings:
      368833f3-8d11-4631-ad8d-e8216490db66:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'blog/{slug}'
        template: blog/category
    structure:
      uid: e8726a0c-c27a-4c81-989d-d88e53e99647
      maxLevels: 1
    entryTypes:
      0255e490-97eb-4a5e-8432-6bb2c1484d64:
        name: Category
        handle: category
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
```

After running the rebuild command:

```
  7d79c3ca-57d0-4828-ac16-0798f5e81770:
    name: 'Categories'
    handle: categories
    type: structure
    enableVersioning: true
    propagateEntries: true
    structure:
      uid: e8726a0c-c27a-4c81-989d-d88e53e99647
      maxLevels: 1
    siteSettings:
      368833f3-8d11-4631-ad8d-e8216490db66:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'blog/{slug}'
        template: blog/category
```

Notice how the whole `entryTypes` node is missing. Thankfully I had a backup but I think this is a pretty serious bug.

### Additional info

- Craft version: 3.1.34
- PHP version: 7.3.3
- Database driver & version: MySQL 5.7.25
