### ISSUE TITLE
Entries not showing up after deployment.

### ISSUE THREAD

**Issue by wrux** [craftcms/cms#4651]
### Description

I have a Structure called `Pages` which works great on my localhost. When it comes to deploying the website i'm not sure what the issue is. 

Before I deploy; I am running `./craft settings/rebuild`. If I check my `config/project.yml` file it contains this:

```
sections:
  21e80bf5-5bf0-4acd-89fa-e108f377f367:
    name: Pages
    handle: Pages
    type: structure
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      0bbf44af-5493-45e6-a8fd-711fbf205c27:
        enabledByDefault: true
        hasUrls: true
        uriFormat: '{parent.uri}/{slug}'
        template: pages/page
      62a954cf-14e6-4afc-a4ee-721a1fa504ce:
        enabledByDefault: true
        hasUrls: true
        uriFormat: '{parent.uri}/{slug}'
        template: pages/page
      b24e91d9-c16e-4418-a2be-f784c1a5db73:
        enabledByDefault: true
        hasUrls: true
        uriFormat: '{parent.uri}/{slug}'
        template: pages/page
      dcd40638-52ee-4f8e-944b-be8663f015d6:
        enabledByDefault: true
        hasUrls: true
        uriFormat: '{parent.uri}/{slug}'
        template: pages/page
    structure:
      uid: 3051f9fb-d940-42a7-a2bf-1a4dcfbf0bfe
      maxLevels: null
    entryTypes:
      33ed925f-348c-4c9d-bf8e-a18f36ffa2f9:
        name: Homepage
        handle: homepage
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 2
        fieldLayouts:
          b04b3c2b-b371-4c33-8813-5dd41ba38143:
            tabs:
              -
                name: Content
                sortOrder: 1
                fields:
                  7dfc068b-dcde-47e8-92ab-17054e23cd28:
                    required: false
                    sortOrder: 2
      96020cb2-dbdb-42c7-bcae-66762fd7b98c:
        name: Page
        handle: page
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          63ce77f0-af11-4304-b21d-c1bc6d0c8bb6:
            tabs:
              -
                name: Content
                sortOrder: 1
                fields:
                  0556df33-f19f-4a6e-a26b-73be1b719674:
                    required: false
                    sortOrder: 1
                  7dfc068b-dcde-47e8-92ab-17054e23cd28:
                    required: false
                    sortOrder: 2
```

When I deploy my changes and run `./craft project-config/sync` the Entries section isn't showing up in Admin. I added mutiple other different entry types to test but nothing seems to work. 

Am I doing something wrong here? 

Is it a problem with the URLs maybe?

### Steps to reproduce

1. Create a Pages entry type
2. Run `./craft settings/rebuild`
3. Deploy
4. Run `./craft project-config/sync` on production
5. Go to admin and there is no Entries sectioon in the sidebar. If I put the production server inito Dev and go to the Settings there is also nothing in the Entries settings. 

### Additional info

- Craft version: 3.2.0
- PHP version: 7.1
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

- Asset Rev 6.0.2
- Commerce Currency Prices	2.4.2
- Contact Form	2.2.5
- Craft Commerce 2.1.10
- Inline SVG 0.1.1
- Navigation 1.1.12
- Neo	2.3.6
- Redactor	2.3.3.2
- Sentry 1.5.1
- SEO	3.5.4
