### ISSUE TITLE
Codeception Unit Testing Wipes Pre-configured DB

### ISSUE THREAD

**Issue by markhuot** [craftcms/cms#4689]
When running `vendor/bin/codecept run unit` my database is cleared out and apparently reset to a default state. My sections, entries, and users are all wiped out. I have `project.yaml` set up for my regular website as well as the `tests/config/project.yaml` but I can't seem to figure out how to seed the unit tests.

I was reading about https://docs.craftcms.com/v3/testing/testing-craft/fixtures.html#craft-specific-data, but that confused me because I already have that sort of thing set up in my `project.yaml` so it seems redundant to have to define my sections in two places.

I think this is a dumb question and if this is better placed on Stack Overflow I'm happy to put it there, just let me know.

### Steps to reproduce

1. Install Craft
2. Configure craft with a single section, I named my "Articles"
3. Follow the testing guidelines, https://docs.craftcms.com/v3/testing/testing-craft/getting-started.html
4. Run `vendor/bin/codecept run unit` with the default "edition" test, no need for anything more.
5. Notice that the DB is cleared out on run.

### Additional info

- Craft version: 3.2.6
- PHP version: 7.2.1
- Database driver & version: mysql 5.6.38
- Plugins & versions: n/a

**Comment by aaronbushnell** [comment]
Hey @markhuot—not sure if you did this or not, but the `.env` in your `tests/` directory should use a database different than your actual site. Or if you want to use the same database you'll need to set these values to `false` in your `codeception.yml` file:

```yml
dbSetup: {clean: false, setupCraft: false} # Setting these to true will wipe the DB and re-seed Craft with a new DB
```

**Comment by markhuot** [comment]
Thanks @aaronbushnell!

I guess I’m confused then, if the default is the recommended approach, and I want my unit tests to be pure which each invocation then what is the best way to re-seed Craft with the correct Sections and entries in those sections?

Is it `project.yaml` with entry fixtures?

**Comment by aaronbushnell** [comment]
> Is it `project.yaml` with entry fixtures?

That's what I've been doing! Which I _think_ makes sense because you then focus less on your specific data and you're just seeding a dummy DB and generating your schema off what's in your `project.yaml` file.

I was pointed to this [Db Codeception guide](https://codeception.com/docs/modules/Db) if you're interested in seeding a different database (as opposed to the dummy Craft one).

Hope that helps. I've been trying to wrap my brain around around this stuff, too, and the testing channel in the Craft Discord has helped a bunch!

**Comment by markhuot** [comment]
Ahhh! I didn't realize/see the extra configuration in `codeception.yml`. The default copy/paste config doesn't specify [a `project.yaml`](https://docs.craftcms.com/v3/testing/framework/config-options.html#config-options). I added that and everything is preserved, yay!

I'm going to close this, but I'm curious: do you share a single `project.yaml` between the site and your test suite? Or do you remember to copy/paste your site config over to your tests after making changes?

**Comment by aaronbushnell** [comment]
So I _think_ this dynamically gets pulled if you have `projectConfig` set! Here's what ours looks like:

```yaml
actor: Tester
paths:
  tests: tests
  log: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
settings:
  bootstrap: _bootstrap.php
params:
  - tests/.env
modules:
  config:
    \craft\test\Craft:
      configFile: 'tests/_craft/config/test.php'
      entryUrl: 'http://exampledomain.test/index.php'
      projectConfig: {file: 'config/project.yaml'}              # Pulls the project.yaml Craft builds from the actual site
      migrations: []
      plugins: []
      cleanup: true
      transaction: true
      dbSetup: {clean: true, setupCraft: true}                  # Setting this to true wipes the DB on each test run and seeds a new one
```
