### ISSUE TITLE
Robust code

### ISSUE THREAD

**Issue by szepeviktor** [craftcms/cms#4740]
Hello!

Please consider using @phpstan
[The PHAR file is here](https://github.com/phpstan/phpstan-shim/blob/master/phpstan.phar)
On Level 0 it shows 5 issues, on Level max 3995
It is tricky to get started, described below in the NEON file.

`phpstan.neon.dist`

```yaml
# mkdir config storage
# ln -s ../.. vendor/craftcms/cms
# phpstan analyse -l 0

includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - %currentWorkingDirectory%/src/
    autoload_files:
        # <?php define('CRAFT_VENDOR_PATH', dirname(__DIR__, 2).'/vendor/');
        - %currentWorkingDirectory%/tests/static-analysis/bootstrap.php
        - %currentWorkingDirectory%/vendor/twig/twig/src/Extension/CoreExtension.php
        - %currentWorkingDirectory%/bootstrap/console.php
#        - %currentWorkingDirectory%/bootstrap/web.php
    excludes_analyse:
        - %currentWorkingDirectory%/src/test/
        - %currentWorkingDirectory%/src/views/
```
