### ISSUE TITLE
Type error thrown on project-config/sync when changing data type

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/cms#4932]
### Description
Looks like in instances (though, can only account for this one) where a project.yaml value is changing from a string to a _dictionary_ type, an error is thrown on sync.

```
error: Argument 1 passed to craft\services\ProjectConfig::_traverseDataArray() must be of the type array, string given, called in .../vendor/craftcms/cms/
src/services/ProjectConfig.php on line 1358
```
 
*Note*: This is actually only thrown once surprisingly (like on a deploy causing it to fail 😉) but if you run `project-config/sync` again, it succeeds. 

### Steps to reproduce

1. Install bugsnag plugin
2. Navigate to settings screen and do initial save if needed with dummy values:

![image](https://user-images.githubusercontent.com/1377169/64814839-db5b8000-d569-11e9-83a4-e9fa029881f8.png)

Output should be:
```
bugsnag:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      enabled: ''
      serverApiKey: '1234567890'
      releaseStage: ''
      appVersion: ''
      notifyReleaseStages:
        - production
      filters:
        - password
      blacklist: ''
```
3. Manually replace `blacklist:` string value:
```
bugsnag:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      enabled: ''
      serverApiKey: '1234567890'
      releaseStage: ''
      appVersion: ''
      notifyReleaseStages:
        - production
      filters:
        - password
      blacklist:
        -
          label: 404s
          class: yii\web\NotFoundHttpException
```
4. Run `project-config/sync` and observe type error
5. Run `project-config/sync` and observe changes applied successfully!
### Additional info

- Craft version: 3.3.3
- PHP version: 7.1.30
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Bugsnag 2.0.5
