### ISSUE TITLE
project.yaml schema version mismatch errors, but the version numbers match

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#4998]
### Description
I am getting the following errors:

```
Your project.yaml file was created for different versions of Craft and/or plugins than what’s currently installed.

Craft CMS currently installed has the schema version of 3.3.3 (expected 3.2.16)
Rollbar currently installed has the schema version of 1.0.0 (expected 3.0.4)
Submissions currently installed has the schema version of 1.0.0 (expected 2.1.0)
Try running composer install from your terminal to resolve.
```

Running `composer install` has no effect.
Deleting the `vendor` folder then running `composer install` has no effect.

When I look at my `project.yaml` file, for example, Craft CMS is installed with the correct schema version; there is no mention of `3.3.3` in the whole file:

```
system:
  edition: pro
  live: true
  name: ECL
  timeZone: Europe/London
  schemaVersion: 3.2.16
```

Rollbar and Submissions are two of our custom plugins which we install through our VCS, but the schema versions in `project.yaml` are what the error message says it's expecting:

```
  submissions:
    settings: null
    licenseKey: null
    enabled: '1'
    schemaVersion: 2.1.0
```

```
  rollbar:
    settings: null
    licenseKey: null
    enabled: '1'
    schemaVersion: 3.0.4
```

Could this be an issue with installing plugins from a private instance of GitLab, which is where Submissions and Rollbar are stored?

### Additional info

- Craft version: 3.3.4.1
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.24
