### ISSUE TITLE
Link not visible in system emails

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#5155]
### Description
Related to #3495

System emails are sent with invalid HTML, resulting in (for example) the activation link not being visible to end users.

Output:

```<html>
<body>
    <div style=3D"max-width: 500px; font-size: 13px; line-height: 18px; fon=
t-family: HelveticaNeue, sans-serif;">
        <p>Hey xxx,</p>
<p>To reset your xxx CMS password, click on this link:</p>
<p><xxx/admin/actions/users/set=
-password?code=3DFvO5Gxb5M-auoqEZ85rZUM6DTviFytwN&id=3Df20b2348-779d-41e6-8=
056-721efe0b568e></p>
<p>If you were not expecting this email, just ignore it.</p>

    </div>
</body>
</html>
```

### Steps to reproduce

1. Install craft
2. Configure mail as follows (excerpt from our `project.yaml` config)
```
email:
  fromEmail: $SMTP_MAILFROM
  fromName: 'xxx CMS'
  template: ''
  transportType: craft\mail\transportadapters\Smtp
  transportSettings:
    host: $SMTP_HOST
    port: $SMTP_PORT
    useAuthentication: ''
    username: ''
    password: ''
    encryptionMethod: ''
    timeout: '10'
```
4. Enable craft headless mode (not sure if that affects this issue) -- for reference, our full general.php config:
```
<?php
/**
 * General Configuration
 *
 * All of your system's general configuration settings go in here. You can see a
 * list of the available settings in vendor/craftcms/cms/src/config/GeneralConfig.php.
 */

return [
    // Global settings
    '*' => [
        // Default Week Start Day (0 = Sunday, 1 = Monday...)
        'defaultWeekStartDay' => 1,

        // Enable CSRF Protection (recommended, will be enabled by default in Craft 3)
        'enableCsrfProtection' => true,

        // Whether "index.php" should be visible in URLs
        'omitScriptNameInUrls' => true,

        // Control Panel trigger word
        'cpTrigger' => 'admin',

        // The secure key Craft will use for hashing and encrypting data
        'securityKey' => getenv('SECURITY_KEY'),

        'useProjectConfigFile' => true,
        'allowAdminChanges' => false,
        'allowUpdates' => false,
        'preventUserEnumeration' => true,
        'runQueueAutomatically' => false,
        'sendPoweredByHeader' => false,
        'useFileLocks' => true,
        'useSecureCookies' => true,
        'useSslOnTokenizedUrls' => true,
        'headlessMode' => true
    ],

    // Dev environment settings
    'dev' => [
        // Dev Mode (see https://craftcms.com/support/dev-mode)
        'devMode' => true,
        'allowAdminChanges' => true,
        'allowUpdates' => true,
        'runQueueAutomatically' => true
    ],

    // Staging environment settings
    'staging' => [
        // Base site URL
        'siteUrl' => null,
    ],

    // Production environment settings
    'production' => [
        // Base site URL
        'siteUrl' => null,
    ],
];
```
5. Configure `.env` variables to establish a working connection with SMTP
6. Request a password reset

### Additional info

- Craft version: 3.3.10
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Plugins & versions: 
```
  bugsnag:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  schema:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    schemaVersion: 2.3.0
    enabled: true
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
```
