### ISSUE TITLE
"Fatal error: Class 'Craft' not found" when running tests on CircleCI

### ISSUE THREAD

**Issue by dce** [craftcms/cms#5164]
### Description

I have a test suite that runs in my local Docker environment, and I'm trying to get it running on CircleCI. Trouble is, no matter what I try, I get some variant of this error:

```
./vendor/bin/codecept run
Codeception PHP Testing Framework v3.0.2
Powered by PHPUnit 7.5.13 by Sebastian Bergmann and contributors.
Running with seed: 


Acceptance Tests (0) ---------------------------------------
------------------------------------------------------------

Fatal error: Class 'Craft' not found in /home/circleci/project/vendor/codeception/codeception/src/Codeception/Lib/Di.php on line 84

Call Stack:
    0.0001     378456   1. {main}() /home/circleci/project/vendor/codeception/codeception/codecept:0
    0.0599    8944400   2. Codeception\Application->run() /home/circleci/project/vendor/codeception/codeception/codecept:43
    0.0599    8944400   3. Codeception\Application->run() /home/circleci/project/vendor/codeception/codeception/src/Codeception/Application.php:107
    0.0663    9109568   4. Codeception\Application->doRun() /home/circleci/project/vendor/symfony/console/Application.php:149
    0.0666    9113136   5. Codeception\Application->doRunCommand() /home/circleci/project/vendor/symfony/console/Application.php:273
    0.0667    9113136   6. Codeception\Command\Run->run() /home/circleci/project/vendor/symfony/console/Application.php:934
    0.0670    9116552   7. Codeception\Command\Run->execute() /home/circleci/project/vendor/symfony/console/Command/Command.php:255
    0.0820   10186944   8. Codeception\Command\Run->runSuites() /home/circleci/project/vendor/codeception/codeception/src/Codeception/Command/Run.php:391
    0.1072   12089368   9. Codeception\Codecept->run() /home/circleci/project/vendor/codeception/codeception/src/Codeception/Command/Run.php:496
    0.1080   12092568  10. Codeception\Codecept->runSuite() /home/circleci/project/vendor/codeception/codeception/src/Codeception/Codecept.php:160
    0.1080   12092824  11. Codeception\SuiteManager->__construct() /home/circleci/project/vendor/codeception/codeception/src/Codeception/Codecept.php:188
    0.1081   12093864  12. Codeception\Lib\ModuleContainer->create() /home/circleci/project/vendor/codeception/codeception/src/Codeception/SuiteManager.php:67
    0.1092   12293544  13. Codeception\Lib\Di->instantiate() /home/circleci/project/vendor/codeception/codeception/src/Codeception/Lib/ModuleContainer.php:92
    0.1092   12293832  14. ReflectionClass->newInstanceArgs() /home/circleci/project/vendor/codeception/codeception/src/Codeception/Lib/Di.php:84




FATAL ERROR. TESTS NOT FINISHED.
Class 'Craft' not found 
in /home/circleci/project/vendor/codeception/codeception/src/Codeception/Lib/Di.php:84
Exited with code 255
```

The issue seems connected to the references to `craft\test\Craft` in `codeception.yml`, `test/functional.suite.yml` and `test/unit.suit.yml` -- if I remove those, the error goes away (and new ones appear, of course).

This is almost certainly an issue with my code/config and not Craft, but I'm curious if anyone else has encountered anything like this. Thank you.

### Steps to reproduce

1. `.circleci/config.yml`:

```yaml
version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      - image: mariadb:10.3
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: clientname
          MYSQL_USER: clientname
          MYSQL_PASSWORD: clientname
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install libpng-dev
      - run: sudo docker-php-ext-install gd pdo_mysql
      - restore_cache:
          keys:
            - composer-{{ checksum "composer.lock" }}
      - run: composer install
      - save_cache:
          paths:
            - vendor
          key: composer-{{ checksum "composer.lock" }}
      - run: cp .circleci/.env tests
      - run: ./vendor/bin/codecept run
```

2. `codeception.yml`

```yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
bootstrap: _bootstrap.php
params:
    - tests/.env
modules:
    config:
        \craft\test\Craft:
            configFile: 'tests/_craft/config/test.php'
            entryUrl: 'http://clientname.test/index.php'
            entryScript: ''
            projectConfig: {file: 'config/project.yaml'}
            migrations: []
            plugins: []
            cleanup: true
            transaction: true
            dbSetup: {clean: true, setupCraft: true}
```

Not sure what other info is relevant but happy to provide anything.

### Additional info

- Craft version: 3.3.7
- PHP version: 7.1
- Database driver & version: MariaDB 10.3
- Plugins & versions: 

```
  3     "clubstudioltd/craft-asset-rev": "6.0.2",
  4     "craftcms/cms": "3.3.7",
  5     "craftcms/redactor": "2.4.0",
  6     "dolphiq/redirect": "1.0.23",
  7     "rias/craft-width-fieldtype": "1.0.6",
  8     "shennyg/azure-blob-remote-volume": "1.0.2",
  9     "solspace/craft3-calendar": "2.0.24",
 10     "verbb/navigation": "1.1.13",
 11     "verbb/super-table": "2.3.0",
 12     "viget/craft-video-embed": "^1.2",
 13     "vlucas/phpdotenv": "^3.4"
```

**Comment by gtettelaar** [comment]
Do these tests run locally? Also what does your `tests/_craft/config/test.php` & `tests/_bootstrap.php` files like?

**Comment by dce** [comment]
Yes, they run properly in the local Docker environment I use for development.

`tests/_craft/config/test.php`:

```php
<?php
use craft\test\TestSetup;

return TestSetup::createTestCraftObjectConfig();
```

`tests/_bootstrap.php`:

```php
<?php

use craft\test\TestSetup;

ini_set('date.timezone', 'UTC');

// Use the current installation of Craft
define('CRAFT_STORAGE_PATH', __DIR__ . '/_craft/storage');
define('CRAFT_TEMPLATES_PATH', dirname(__DIR__) . '/templates');
define('CRAFT_CONFIG_PATH', __DIR__ . '/_craft/config');
define('CRAFT_MIGRATIONS_PATH', __DIR__ . '/_craft/migrations');
define('CRAFT_TRANSLATIONS_PATH', __DIR__ . '/_craft/translations');
define('CRAFT_VENDOR_PATH', dirname(__DIR__).'/vendor');

TestSetup::configureCraft();
```

**Comment by gtettelaar** [comment]
Hmm that looks all normal. If you can share your `unit.suite.yaml` and `functional.suite.yaml` I can try to reproduce it locally...

**Comment by dce** [comment]
```yaml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests.

actor: UnitTester
modules:
    enabled:
        - \craft\test\Craft
        - Asserts
        - \Helper\Unit
    step_decorators: ~
```

```
# Codeception Test Suite Configuration
#
# Suite for functional tests
# Emulate web requests and make application process them
# Include one of framework modules (Symfony2, Yii2, Laravel5) to use it
# Remove this suite if you don't use frameworks

actor: FunctionalTester
modules:
    enabled:
        - \craft\test\Craft
        - \Helper\Functional
    step_decorators: ~
```
