### ISSUE TITLE
project-config/rebuild deletes preview targets from project.yaml

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#5215]
### Description

When saving section settings from cp, the preview targets are saved to project.yaml
```
previewTargets:
      -
        label: Client
        urlFormat: '/client#/{site.handle}/film/{sourceId}/{slug}'
```

When running project-config/rebuild, no preview targets are no longer present in project.yaml and in info/config column.

### Steps to reproduce

see above.

### Additional info

- Craft version: 3.3.15
- PHP version: 7.2.14
- Database driver & version:
- Plugins & versions:
