### ISSUE TITLE
Remove plugin by composer does not update project-config YAML

### ISSUE THREAD

**Issue by bertoost** [craftcms/cms#5465]
### Description

When I remove a plugin via composer, it is perfectly removed and the composer json/lock files are updated accordingly.
Unfortunate the plugin entry still exists in the project.yaml file. Shouldn't it be removed from there as well?

I mean this part from the config;

```yml
plugins:
  plugin-handle:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
```

### Steps to reproduce

1. Remove plugin by using `composer remove <plugin>`
2. Check `project.yaml` file

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.4.1
