### ISSUE TITLE
UI: Blurred background when modals open obscures content

### ISSUE THREAD

**Issue by mlathrom** [craftcms/cms#5651]
### Description
The background blurring when a modal is open makes it impossible to reference things on the page.

I often need to reference things I've already entered on an entry page while working with the content of a modal. Since the blur only really serves to highlight the modal, then perhaps a simple white overlay would suffice.

![blur](https://user-images.githubusercontent.com/373889/74490569-c61eb080-4e7d-11ea-8e47-42183e67f103.jpg)

Vs

![no-blur](https://user-images.githubusercontent.com/373889/74490562-c1f29300-4e7d-11ea-960c-49d1b14e9912.jpg)

### Additional info

- Craft version: 3.4
- PHP version: 7.3
- Database driver & version: MySQL 5.7

**Comment by dennisfrank** [comment]
I also find the effect a little over-the-top. I use some custom CSS, which reduces the effect and removes it completely on hover:

SCSS
```scss
/* Modal */
.modal-shade {
  backdrop-filter: blur(2px);
  transition: backdrop-filter .2s ease-out;

  &:hover {
    backdrop-filter: blur(0);
  }
}
```

CSS
```css
.modal-shade {
  -webkit-backdrop-filter: blur(2px);
  backdrop-filter: blur(2px);
  transition: -webkit-backdrop-filter 0.2s ease-out;
  transition: backdrop-filter 0.2s ease-out;
  transition: backdrop-filter 0.2s ease-out, -webkit-backdrop-filter 0.2s ease-out;
}

.modal-shade:hover {
  -webkit-backdrop-filter: blur(0);
  backdrop-filter: blur(0);
}
```

![image](https://user-images.githubusercontent.com/65968/74540680-7fde5580-4f40-11ea-9117-53684929429e.png)
