### ISSUE TITLE
Project.yaml not populating dropdown field options

### ISSUE THREAD

**Issue by askogrand** [craftcms/cms#5777]
### Description

If a `project.yaml` file has a dropdown field with correct values, and the project file is up to date by running `./craft project-config/sync`, I see empty rows of dropdown options inside the database that will not update no matter how many times I re-sync.

Example data:
```
  f8b47509-bf9f-446b-803d-f3c6a99f289d:
    contentColumnType: string
    fieldGroup: 9f9c2a4e-2177-48b9-86d1-62f95652d9f8
    handle: documentType
    instructions: ""
    name: "Document Type"
    searchable: true
    settings:
      optgroups: true
      options:
        - __assoc__:
            - - label
              - PowerPoint
            - - value
              - powerpoint
            - - default
              - ""
        - __assoc__:
            - - label
              - Word
            - - value
              - word
            - - default
              - ""
```
Relevant field detail:
![image](https://user-images.githubusercontent.com/503729/76329789-658b6380-62c3-11ea-817f-bd6259da2c84.png)
 
The field has the _correct number_ of dropdown options, but all options are blank.

### Steps to reproduce
1. Create and populate a field with dropdown options
2. Ensure that project.yaml is up to date by running `./craft project-config/sync`
3. Deploy this project file to a remote environment without the field, sync the project.yaml file
3. Check your remote field settings for any dropdown field to see a list of empty options

### Additional info

- Craft version: Craft Pro 3.4.9
- PHP version: 7.2.11
- Database driver & version: PostgreSQL 9.6.17
- Plugins & versions:
```
Architect 2.3.2
Azure Blob Remote Volume 1.0.2
Chunked File Uploads 1.0.1
Cloner 1.1.0
Field Manager 2.1.1
Freeform 3.6.5
Maps 3.8.2
Neo 2.6.3
Redactor	 
Sift dev-master
Tags 1.0.6
Workflow 1.4.2
```
