### ISSUE TITLE
Upgrading from Craft 2 -> Craft 3.4 using Project Config results in 0 entries, but is solvable...

### ISSUE THREAD

**Issue by ldstevens** [craftcms/cms#5914]
### Description

I'm working on an upgrade of a large-ish site from 2.7 to 3.4.

We have:
- Production on 2.7
- Staging on 3.4
- Development on 3.4

The upgrade has been in the works for a while, and we originally migrated from 2.7 -> 3.1 (in the dev environment) without too many issues.

We then continued development, enabled Project Config, and upgraded the development site & staging to 3.4.

However, when I went back to migrate a current v2 DB (from production) to 3.4 (in development), the DB upgrade worked, but running Project Config resulted in missing sections and zero entry counts (a lot of 0/0 results).

(The project.yaml file came from the staging setup, which was the same as development site pre-v2 DB migration.)

Checking the craft_content table showed the data was still there, it just wasn't showing up in the CP.

Looking through the CP I noticed there was now a choice of Sites for entries, and changing Site showed some (but not all) of the missing sections/entries. (The actual website has always just been one Site in Craft.)

Armed with that clue, I diffed the (I *think*) v2->v3.4 upgrade result project.yaml against the used-for-upgrade v2->v3.1->v3.4 project.yaml, and spotted different UIDs for `siteGroups` and `sites`.

### project.yaml from v2->v3.4 *before* applying staging project.yaml
```
siteGroups:
  ab10466f-8da1-4002-8f17-df13e03a5c71:
sites:
  a8f2ff2e-97e6-4a29-92a3-41c6705ac7a1:
```

### v2->v3.1-v3.4 staging project.yaml applied that creates the bad upgrade
```
siteGroups:
  426b2334-7102-458d-8e9f-e76b75649da3:
sites:
  f79780d1-a25f-4bf8-8370-3841a4884830:
```

The fix was creating a hybrid project.yaml using everything from the v3.4 staging version, but changing siteGroups & sites to match the existing UIDs, i.e.:
```
siteGroups:
  ab10466f-8da1-4002-8f17-df13e03a5c71:
sites:
  a8f2ff2e-97e6-4a29-92a3-41c6705ac7a1:
```

That solved the issue. So it seems (at a guess!) like something changed in the way these UIDs are created such that going from (a) v2->v3.1->v3.4 gives a different result to (b) v2->v3.4, and therefore applying project.yaml from (a) to (b) results in sad times.

Also, Project Config is amazing in theory and when you've got a solid workflow in place, but it's (IMO) *way* too high-context for the errors & UI (such as it is) around it at the moment, at least for dumb dumbs like me just trying to upgrade their site. For e.g. on errors: What's "installed" vs "expected"? Why mention composer install when it's actually user screw up? Etc. Too many footguns and too much assumed knowledge IMO. A wizard with more hand-holding and clearer before/after states would be a big help. Just fwiw :)

Thanks! :)
