### ISSUE TITLE
Globalset: Couldn’t propagate element to other site

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#6004]
### Description

I'm setting up a multi-site install locally that my coworker has been working on, and it looks like there is an issue propagating a globalset to additional sites during installation.

```
    > applying existing project config ... Exception: Couldn’t propagate element to other site. (/var/www/html/vendor/craftcms/cms/src/services/Elements.php:2343)
#0 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2134): craft\services\Elements->_propagateElement(Object(craft\elements\GlobalSet), Array, Object(craft\elements\GlobalSet))
#1 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(531): craft\services\Elements->_saveElementInternal(Object(craft\elements\GlobalSet), false, true, true)
#2 /var/www/html/vendor/craftcms/cms/src/services/Globals.php(434): craft\services\Elements->saveElement(Object(craft\elements\GlobalSet), false)
#3 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1102): craft\services\Globals->handleChangedGlobalSet(Object(craft\events\ConfigEvent))
#4 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#5 /var/www/html/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#6 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(675): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#7 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1204): craft\services\ProjectConfig->processConfigChanges('globalSets.bcc2...', false, NULL, true)
#8 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(539): craft\services\ProjectConfig->_applyChanges(Array)
#9 /var/www/html/vendor/craftcms/cms/src/migrations/Install.php(1077): craft\services\ProjectConfig->applyYamlChanges()
#10 /var/www/html/vendor/craftcms/cms/src/migrations/Install.php(68): craft\migrations\Install->insertDefaultData()
#11 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\Install->safeUp()
#12 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#13 /var/www/html/vendor/craftcms/cms/src/console/controllers/InstallController.php(155): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
#14 [internal function]: craft\console\controllers\InstallController->actionCraft()
#15 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('', Array)
#18 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(187): yii\console\Controller->runAction('', Array)
#19 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
#20 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
#21 /var/www/html/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('install', Array)
#22 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
#23 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#24 /var/www/html/craft(22): yii\base\Application->run()
#25 {main}
Exception 'craft\errors\MigrationException' with message 'An error occurred while executing the "craft\migrations\Install migration: Couldn’t propagate element to other site.'

in /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php:250

Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/console/controllers/InstallController.php(155): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
#1 [internal function]: craft\console\controllers\InstallController->actionCraft()
#2 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('', Array)
#5 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(187): yii\console\Controller->runAction('', Array)
#6 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
#7 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
#8 /var/www/html/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('install', Array)
#9 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#11 /var/www/html/craft(22): yii\base\Application->run()
#12 {main}
```

Here are the globalsets in the `project.yaml`:

```yaml
globalSets:
  56884ee2-e939-40b6-935f-3a658e9bbfea:
    handle: nav
    name: Navigation
  5c9074fe-0698-4b43-8c03-968771dd81e1:
    fieldLayouts:
      ae9e2cbb-459b-4319-8892-314d1287147a:
        tabs:
          -
            fields:
              38e9d4cd-dd3f-4121-a9e2-08533507fb36:
                required: true
                sortOrder: 2
              65e00c69-0e5a-4873-9a55-c7c066eed53c:
                required: true
                sortOrder: 4
              713b52af-b796-4649-bac0-ede298db1705:
                required: true
                sortOrder: 3
              e8c745d9-3598-4d28-963d-c865e2ea3905:
                required: true
                sortOrder: 1
            name: Content
            sortOrder: 1
    handle: contactInfo
    name: 'Contact Info'
  bcc219ba-885b-4814-897e-30f2d7bd3ad5:
    handle: socialMedia
    name: 'Social Media'
  f9d80ba6-a371-4bfe-8bfa-26aeec00c983:
    fieldLayouts:
      ee4c1ab9-e396-4a35-9c7a-fb2932368df5:
        tabs:
          -
            fields:
              4600bb61-602c-49ec-a0b4-3c7e0d9c1e86:
                required: false
                sortOrder: 1
            name: Content
            sortOrder: 1
    handle: socialMedia
    name: 'Social Media'
```

Let me know if it would be helpful to send the full `project.yaml` and composer files.

### Steps to reproduce

1. Install Craft with an existing `project.yaml` with a global and multi-site

### Additional info

- Craft version: 3.4.16
- PHP version: 7.3.16
- Database driver & version: MySQL 5.7.29

**Comment by brandonkelly** [comment]
Search your log files for `Couldn’t propagate element to other site due to validation errors:` – an error should have been logged right before that exception was thrown, which explains the issue.

**Comment by davist11** [comment]
Aha! Looks like the global set was duplicated with the same name in the `project.yaml`.

```yaml
  bcc219ba-885b-4814-897e-30f2d7bd3ad5:
    handle: socialMedia
    name: 'Social Media'
```

Not sure what exactly happened here, but removing that seems to fix the problem. Thanks!
