### ISSUE TITLE
CraftConnector getEmails TypeError

### ISSUE THREAD

**Issue by juban** [craftcms/cms#6259]
### Description
Hi,

I'm trying to setup acceptante tests using Codeception and email part of `craft\test\Craft` module.

However, when using the `seeEmailIsSent` assertion, the following error is thrown:
` [TypeError] Return value of craft\test\CraftConnector::getEmails() must be of the type array, null returned`

For some reason, the return statement doesn't seem to return the expected array.

I've tried various mailer configurations with no success.

### Steps to reproduce

Use `$I->seeEmailIsSent` assertion in acceptance test

### Additional info

- Craft version: 3.4.24
- PHP version: 7.4
- Database driver & version: MariaDB 10.2
- Plugins & versions: Elements Panel 1.0.0, Redactor 2.6.1, Retcon 2.1.0, SEO 3.6.5.1, Super Table 2.5.1, Twigpack 1.2.2, Typography 1.1.38

**Comment by angrybrad** [comment]
Potentially related to https://github.com/craftcms/cms/pull/6263, which will be included in the next release.  Want to pull that in early and see if it's related?

**Comment by juban** [comment]
Hi Brad. Indeed, looks like it's related because I'm setting dynamically the mailer configuration in order to activate SMTP authentification or not depending on environment. I'll try the fix and let you know. Thx.

**Comment by juban** [comment]
Unfortunately, I tried to use the new CraftConnector version and it doesn't change anything for me.

I'm using the following acceptance suite configuration:

```yaml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:

  enabled:
    - PhpBrowser:
        url: https://some-domain.test/
    - \craft\test\Craft:
        part:
         - init
         - orm
         - email
        cleanup: false
        transaction: false
    - \Helper\Acceptance
  step_decorators: ~
```
I'm only using parts of `craft\test\Craft` here. Could this be related to the issue?
