### ISSUE TITLE
[Testing] Cannot successfully extend AssetFixture

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#6309]
### Description

I'm working on adding an asset fixture to my test suite, and having a number of issues. Here is the asset fixture:

```php
<?php

namespace client\tests\fixtures;

use Craft;
use craft\test\fixtures\elements\AssetFixture;

class AssetsFixture extends AssetFixture
{
    public $dataFile = __DIR__ . '/data/assets.php';
}
```

Here is the data:

```php
<?php

return [
    [
        'tempFilePath' => CRAFT_STORAGE_PATH . '/runtime/temp/sample.png',
        'filename' => 'sample.png',
        'volumeId' => $this->volumeIds['parts'],
        'folderId' => 1,
    ],
];
```

The asset exists:

![image](https://user-images.githubusercontent.com/199985/86364046-ada10e00-bc45-11ea-97d3-7a0110ca52e2.png)

Here's where I'm loading the fixture:

```php
<?php

namespace client\tests;

use Codeception\Test\Unit;

use UnitTester;
use Craft;
use client\tests\fixtures\AssetsFixture;

class WebTest extends Unit
{
    /**
     * @var UnitTester
     */
    protected $tester;

    public function _fixtures(): array
    {
        return [
            'assets' => [
                'class' => AssetsFixture::class,
            ],
        ];
    }
}
```

When I run that, I get the following error:

```
[yii\base\ErrorException] copy(/var/www/html/vendor/craftcms/cms/tests/_craft/assets/sample.jpg): failed to open stream: No such file or directory  
```

When I dig into the AssetFixture class I'm extending, this makes sense because of how these properties are being set:

https://github.com/craftcms/cms/blob/74684923842c6667690e8a85f543f5e5a976adf8/src/test/fixtures/elements/AssetFixture.php#L76-L77

Am I doing something wrong? I ended up overriding the `init()` method in my fixture and got some progress:

```php
public function init()
{
    // parent::init();

    foreach (Craft::$app->getVolumes()->getAllVolumes() as $volume) {
        $this->volumeIds[$volume->handle] = $volume->id;
        $this->folderIds[$volume->handle] = VolumeFolder::findOne([
            'parentId' => null,
            'name' => $volume->name,
            'volumeId' => $volume->id,
        ])->id;
    }

    $this->sourceAssetPath = dirname(__FILE__, 3) . '/tests/_craft/assets/';
    $this->destinationAssetPath = dirname(__FILE__, 3) . '/tests/_craft/storage/runtime/temp/';

    if (!is_dir($this->destinationAssetPath)) {
        FileHelper::createDirectory($this->destinationAssetPath);
    }

    $data = require $this->dataFile;

    foreach ($data as $fileName) {
        $this->files[] = $fileName;
    }
}
```

But then I got this error:

```
[Aws\Sts\Exception\StsException] Error executing "GetSessionToken" on "https://sts.amazonaws.com"; AWS HTTP error: Client error: `POST https://sts.amazonaws.com` resulted in a `403 Forbidden` response:
\<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  \<Error>
    \<Type>Sender\</Type>
    \<Code>InvalidCli (truncated...)
 InvalidClientTokenId (client): The security token included in the request is invalid. - \<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  \<Error>
    \<Type>Sender\</Type>
    \<Code>InvalidClientTokenId\</Code>
    \<Message>The security token included in the request is invalid.\</Message>
  \</Error>
  \<RequestId>bd3fd383-a8de-4c50-8254-fe6456818e5b\</RequestId>
\</ErrorResponse>
```

Do I have to create a new volume for the fixture? Or can I use one from the project config? We have one that is just a local volume:

```
volumes:
  226ede78-f450-4729-b5c9-6600a44de7a0:
    fieldLayouts:
      4eaca18b-8af5-4a0e-86aa-1ea281add22f:
        tabs:
          -
            fields:
              6956814b-e08b-4563-865d-9cbe6a2001c8:
                required: false
                sortOrder: 1
            name: Fields
            sortOrder: 1
    handle: parts
    hasUrls: true
    name: 'Parts Kit - Local Files'
    settings:
      path: '@webroot/parts'
    sortOrder: 1
    type: craft\volumes\Local
    url: '@web/parts'
```

What if I don't have any folders in there? Do I need to add a `folderId`?

### Additional info

- Craft version: 3.4.18
- PHP version: 7.3.16
- Database driver & version: MySQL 5.7.29

```
"codeception/codeception": "^4.1",
"codeception/module-asserts": "^1.0.0",
"codeception/module-phpbrowser": "^1.0.0",
"codeception/module-yii2": "^1.1"
```

Let me know what other info I can provide. Thanks!

**Comment by angrybrad** [comment]
Lots going on here.

> [yii\base\ErrorException] copy(/var/www/html/vendor/craftcms/cms/tests/_craft/assets/sample.jpg): failed to open stream: No such file or directory

> When I dig into the AssetFixture class I'm extending, this makes sense because of how these properties are being set:

You're getting that error because Craft is looking for sample.jpg, but everything you've shared is referencing sample.png. Do you have a sample.jpg referenced somewhere else in your test setup?

>         'tempFilePath' => CRAFT_STORAGE_PATH . '/runtime/temp/sample.png',

Make sure your test's main `_bootstrap.php` file is defining CRAFT_STORAGE_PATH as your `tests/_craft/storage/` folder, otherwise that'll pull in the site's main storage folder.

For the rest, it sounds like you're trying to mix project config with database fixture data, which isn't a good idea. See the warning here: https://docs.craftcms.com/v3/testing/framework/config-options.html#projectconfig

**Comment by davist11** [comment]
> You're getting that error because Craft is looking for sample.jpg, but everything you've shared is referencing sample.png.

That's my bad, scrolled too far up in the terminal (I had already corrected the jpg vs png issue). But the bigger problem is that it's looking in the vendor dir right? `/var/www/html/vendor/craftcms/cms/` because of how the property is being set: `$this->sourceAssetPath = dirname(__FILE__, 3) . '/tests/_craft/assets/';` (since this file in in the craft `src` folder)

> Make sure your test's main _bootstrap.php file is defining CRAFT_STORAGE_PATH as your tests/_craft/storage/ folder, otherwise that'll pull in the site's main storage folder.

Yep, it is `define('CRAFT_STORAGE_PATH', __DIR__ . '/_craft/storage');`

When I added that `init()` method into the fixture, it did copy the file over correctly (but then I got that AWS error):

![image](https://user-images.githubusercontent.com/199985/86496179-27babb00-bd4a-11ea-9f3f-fc39c65c3368.png)


> For the rest, it sounds like you're trying to mix project config with database fixture data, which isn't a good idea.

Ok, can you provide some guidance on how to handle this then? Should I be creating a separate volume fixture?

**Comment by angrybrad** [comment]
> Ok, can you provide some guidance on how to handle this then? Should I be creating a separate volume fixture?

If you're using Project Config, then yeah - that's what we do, too.

https://github.com/craftcms/cms/tree/develop/tests/fixtures

> But the bigger problem is that it's looking in the vendor dir right?

What does your project folder structure look like and can you share your `tests/_bootstrap.php` file and your codeception.yml file?

**Comment by davist11** [comment]
Since this is using the `__FILE__` magic constant, and my asset fixture is extending from `src/test/fixtures/elements/AssetFixture.php` then these properties will always be relative to that file:

https://github.com/craftcms/cms/blob/fe2030908d76a029190492e27febdb3c9461638e/src/test/fixtures/elements/AssetFixture.php#L76-L77

And there's no way in my fixture to set the `sourceAssetPath` right? Which explains the error saying it can't find a file to copy in this path `/var/www/html/vendor/craftcms/cms/tests/_craft/assets/`

![image](https://user-images.githubusercontent.com/199985/86512342-4747f700-bdcf-11ea-8d64-afe3b1f65594.png)


```php
<?php

use craft\test\TestSetup;

ini_set('date.timezone', 'UTC');

// Use the current installation of Craft
define('CRAFT_STORAGE_PATH', __DIR__ . '/_craft/storage');
define('CRAFT_TEMPLATES_PATH', __DIR__ . '/_craft/templates');
define('CRAFT_CONFIG_PATH', __DIR__ . '/_craft/config');
define('CRAFT_MIGRATIONS_PATH', __DIR__ . '/_craft/migrations');
define('CRAFT_TRANSLATIONS_PATH', __DIR__ . '/_craft/translations');
define('CRAFT_VENDOR_PATH', dirname(__DIR__).'/vendor');

TestSetup::configureCraft();
```

```yaml
actor: Tester
paths:
  tests: tests
  log: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
bootstrap: _bootstrap.php
modules:
  config:
    \craft\test\Craft:
      configFile: "tests/_craft/config/test.php"
      entryUrl: "http://client.test/index.php"
      projectConfig: { file: 'config/project.yaml', reset: false }
      migrations: []
      plugins: []
      cleanup: true
      transaction: true
      dbSetup: { clean: true, setupCraft: true, applyMigrations: true }
```
