### ISSUE TITLE
Remove meta class from HUD

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/cms#6587]
At the moment the HUD uses the 'meta' styling for the fields. Whilst this make sense in theory (it's narrow, the meta box is narrow) in reality it results in a fairly messy layout with fields much narrower than they need to be.

With a just few minor changes the usability can be much improved:
1. Remove the `.meta` class
2. Add a little padding 
```scss
.hud .elementeditor .main { 
  padding: 0 24px 24px 
}
.preview-thumb-container.editable {
  margin-bottom: 24px;
}
```
Adjusting the width to be proportional with a larger maximum (if needed at all) would solve a couple of other open issues:
```scss
.hud .elementeditor {
  width: 50vw;
  min-width: 320px;
  max-width: 800px; // Or no max?
}
```
Before
![before](https://user-images.githubusercontent.com/1082223/89685554-8daadd00-d8ca-11ea-94b7-44e8448d0030.png)

After
![after](https://user-images.githubusercontent.com/1082223/89685558-8e437380-d8ca-11ea-94bc-cd011aee3531.png)

Would solve #4129 I think.
Solves #5948 if editing via the HUD but not asset entry.

I'm not sure if there any other contexts of the HUD that I haven't considered.
