### ISSUE TITLE
Project config not apply field width for matrixBlockTypes

### ISSUE THREAD

**Issue by jlachancekffein** [craftcms/cms#6764]
When apply project config update, width are not apply to the matrix fields.

In my example, push_content--7e8a9633-d6df-4fc2-8e55-37a1086c8e2e.yaml, the width is define in the yaml file but not apply when imported.

```yaml
field: 8524e3ff-84c6-4e7f-92d1-057b3b51a375
fieldLayouts:
  b0145ebe-b40c-470b-99b3-a217c8721def:
    tabs:
      -
        elements:
          -
            fieldUid: 31adff32-c814-4627-a10b-0150853d606b
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 82caa112-f733-4a2f-8bb1-777062aa3448
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 8cb66cfb-da4d-438b-9b08-776006b75362
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f647d2c5-90f8-44e5-966a-c8e2d98cbe85
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  31adff32-c814-4627-a10b-0150853d606b:
    contentColumnType: text
    fieldGroup: null
    handle: the_title
    instructions: ''
    name: Titre
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  82caa112-f733-4a2f-8bb1-777062aa3448:
    contentColumnType: text
    fieldGroup: null
    handle: the_content
    instructions: ''
    name: Contenu
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  8cb66cfb-da4d-438b-9b08-776006b75362:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:bc4d1d91-3e39-4cfa-b9e2-69e96b7903ae'
      defaultUploadLocationSubpath: images
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:bc4d1d91-3e39-4cfa-b9e2-69e96b7903ae'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:a1b67a2d-5228-4603-8661-7d0093879aa5'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f647d2c5-90f8-44e5-966a-c8e2d98cbe85:
    contentColumnType: string
    fieldGroup: null
    handle: cta
    instructions: ''
    name: Cta
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 3b8506b4-d97a-43e0-9470-935d7445b965
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_15_cta}}'
      fieldLayout: matrix
      maxRows: '1'
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: push_content
name: 'Push content'
sortOrder: 5
```

Versions:

Craft 3.5.7
