### ISSUE TITLE
Changes to Matrix field block types are not saved

### ISSUE THREAD

**Issue by nicbou** [craftcms/cms#6821]
### Description

This is exactly the same issue as #3832 and #6665, but in a newer version

### Steps to reproduce

1. Edit a Matrix field's blocks
2. Save the field
3. The matrix field will not have any blocks types.

* It's not possible to save the field again, because without a block type, it's not valid.
* There are no new files in config/project/matrixBlockTypes (it has full permissions)
* There are no errors
* The POST request contains all the newly created blocks and fields
* This works perfectly fine in Craft 3.4.17.1

### Additional info

- Craft version: 3.5.7 and 3.5.9
- PHP version: 7.3.14
- Database driver & version: MySQL 5.5.5
- Plugins & versions: None.

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Seems like it’s most likely permission related though, even though I know you said that’s not the issue. Try clearing out your entire `config/project/` folder, and then making sure `config/project/` has 777 permissions on it (to be safe).

**Comment by nicbou** [comment]
I recursively set the config directory permissions to 777, and that did not fix the issue.

My live website was still using 3.4.17.1, so I rolled back to that version, and implemented the changes without any issues.

**Comment by brandonkelly** [comment]
Hm ok, well then I will close this for now. If you are able to reproduce again later, let me know.

**Comment by nicbou** [comment]
I think you misunderstood my comment. This is still broken. It was broken by 3.5.*, but since my production server used 3.4.*, I'm just going to wait before I update.

**Comment by brandonkelly** [comment]
I understand it wasn’t resolved for you, but I’m unable to reproduce it, so suspect it’s something environmental, and I don’t have anything else to go on at the moment. Happy to continue helping you with it if you are able to reproduce it again 🙂

**Comment by nicbou** [comment]
I just did a quick test, and I could reproduce it on a separate (but similarly organised) site. I took a video of it: https://imgur.com/a/bjgToD8

Here is the `git status` after creating the field:

```
Änderungen, die nicht zum Commit vorgemerkt sind:
	geändert:       site/craft/config/project/project.yaml

Unversionierte Dateien:
	site/craft/config/project/fields/test--ded3918b-454f-4e56-823a-b55e3ad27593.yaml
```

Here is the content of the field config:

```
fieldGroup: 24164084-1fbe-4cb3-8263-5c3215381e7d
handle: test
instructions: ''
name: Test
searchable: false
settings:
  contentTable: '{{%matrixcontent_test}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
```

I tried changing the permissions to 777 for the config directory and it did not fix it either.
