### ISSUE TITLE
Commerce plugin not getting initialised in Unit testing

### ISSUE THREAD

**Issue by chandamotiyani** [craftcms/cms#6878]
I'm writing unit tests for checking cart manipulations working on our site or not.
I went through https://github.com/craftcms/commerce/tree/develop/tests but in my CartTest.php file following function is throwing an exception not listing out the namespaces

```
protected function _before()
   {
       parent::_before();
       $this->cartController = new CartController('cart', Plugin::getInstance());
       $this->request = Craft::$app->getRequest();
       $this->request->enableCsrfValidation = false;
   }
```
`[Error] Call to a member function getSettings() on null`

Can you please describe or provide proper syntax of how to initialize the Plugin because the following not giving me any idea?

craftcms/cms#1641

**Comment by angrybrad** [comment]
Did you specify the Commerce plugin in your codeception.yml file? https://craftcms.com/docs/3.x/testing/framework/config-options.html#plugins

**Comment by chandamotiyani** [comment]
When I specify it in codeception.yml it gives the following output

```
Codeception PHP Testing Framework v3.1.0
Powered by PHPUnit 8.5.8 by Sebastian Bergmann and contributors.
Running with seed: 


In Craft.php line 294:
                                   
  Invalid plugin handle: commerce  
                                   

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--] [<suite> [<test>]]
```

**Comment by chandamotiyani** [comment]
@angrybrad can you please suggest how to resolve ?
`Invalid plugin handle: commerce  `

**Comment by angrybrad** [comment]
Just tested this on a fresh Craft project and it seems to working as expected for me:

```
actor: Tester
paths:
  tests: tests
  log: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
bootstrap: _bootstrap.php
settings:
params:
  - tests/.env
modules:
  config:
    \craft\test\Craft:
      configFile: 'tests/_craft/config/test.php'
      entryUrl: 'https://test.craftcms.test/index.php'
      projectConfig: {}
      migrations: []
      plugins:
        commerce:
          class: \craft\commerce\Plugin
          handle: commerce
      cleanup: true
      transaction: true
      dbSetup: {clean: true, setupCraft: true}
      fullMock: false
```

Do you have the actual Commerce files in place?  i.e.  `composer require "craftcms/commerce"`?

**Comment by chandamotiyani** [comment]
@angrybrad  Yes, we are using commerce plugin, and its in place in the composer file, can you please suggest how can I troubleshoot this apart from trying in fresh craft cms installation, because I need to make this working in the existing project,

`"craftcms/commerce": "3.1.4",`

Will look forward to some solution for this, thank you!

**Comment by angrybrad** [comment]
The reason I asked the last questions was I was trying to replicate the issue locally on a fresh Craft install, I had forgotten to pull the Commerce files down in composer.json and got the exact same error `Invalid plugin handle: commerce`. Then I pulled them down and it worked as expected.

Are you comfortable with xDebug? If so try setting a breakpoint on `vendor/craftcms/cms/src/test/Craft.php` line 257 where it's loading any plugins listed in the config.

**Comment by chandamotiyani** [comment]
@angrybrad when you say - pulled Commerce files down in composer.json I don't get that, what I need to do that?

**Comment by angrybrad** [comment]
@chandamotiyani If `craftcms/commerce` isn't in your comoser.json file, then running `composer require "craftcms/commerce"`.

If it is already there, then running `composer update`.

**Comment by chandamotiyani** [comment]
@angrybrad running `composer update` also gives the same error `Invalid plugin handle: commerce`

**Comment by angrybrad** [comment]
@chandamotiyani can you zip up your whole site along with a database dump and send it over to support@craftcms.com?

**Comment by chandamotiyani** [comment]
@angrybrad as per the policy signed with the client we cannot do that, any other way?

**Comment by angrybrad** [comment]
What about a simple, reproducible test case with your composer.json, codeception.yml, and tests folder?

**Comment by chandamotiyani** [comment]
We haven't written many tests yet but sending the stuff in the email so that you could reproduce

**Comment by chandamotiyani** [comment]
@angrybrad we aren't using project.yaml and hence the plugin problem have arisen, after changing 1362 in `vendor/craftcms/cms/src/services/Plugins.php` as the following have got it working temporarily, that error isn't coming but what is the long time solution for this?

`if (true && version_compare(Craft::$app->getInfo()->version, '3.1', '<')) `

**Comment by angrybrad** [comment]
I don't think Project Config has anything to do with the behavior you're seeing.

I'd suggest updating to the latest Craft 3.5.x release. You're on 3.4 and some significant bug fixes have been made around testing in 3.5.

Your `codeception.yml` file is also configured to not install the Craft database:

    dbSetup: { clean: false, setupCraft: false }

If Craft isn't installed, then Commerce can't be installed.

Fixing those two issues should resolve this, so going to close the issue out. If you're still stuck, just comment back and can re-open.

**Comment by brianjhanson** [comment]
@angrybrad I'm running into the same issue. 

I dumped L#257 from `vendor/craftcms/cms/src/test/Craft.php` and get what you'd expect

```
array(1) {
  'commerce' =>
  array(2) {
    'class' =>
    string(22) "\craft\commerce\Plugin"
    'handle' =>
    string(8) "commerce"
  }
}
```

Here's my codeception.yml

```yml
actor: Tester
paths:
  tests: tests
  log: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
bootstrap: _bootstrap.php
params:
  - tests/.env
modules:
  config:
    \craft\test\Craft:
      configFile: "tests/_craft/config/test.php"
      entryUrl: "https://{host}/index.php"
      entryScript: 'index.php'
      projectConfig: {}
      migrations: []
      plugins:
        commerce:
          class: '\craft\commerce\Plugin'
          handle: commerce
      cleanup: true
      transaction: false
      dbSetup: { clean: true, setupCraft: true }
```

I'm running Craft 3.5.13.2 and Commerce 3.2.8.1
