### ISSUE TITLE
Tests referencing project config stopped working after update to Craft 3.5.11.1

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#6879]
### Description
We have a number of unit and functional tests that were running just fine on Craft Pro 3.4.28.1, but after updating to Craft 3.5.11.1, they seemed to have stopped working. I made the project config update in my `codeception.yml` to use the folder, but it seems like the project config isn't syncing when running tests. I added a basic test to confirm my suspicions, and this fails:

```php
<?php

namespace client\tests;

use Codeception\Test\Unit;

use UnitTester;
use Craft;

class SampleTest extends Unit
{
    /**
     * @var UnitTester
     */
    protected $tester;

    public function testSelectSection()
    {
        $eventsSection = Craft::$app->sections->getSectionByHandle('events');

        $this->assertNotNull($eventsSection);
    }
}
```

I can confirm that section exists in my project config:

```yaml
enableVersioning: true
handle: events
name: Events
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: siteGroup
siteSettings:
  3b9dd6e4-c699-4bd3-ba03-a1b3f6ba84c6:
    enabledByDefault: true
    hasUrls: true
    template: _elements/event
    uriFormat: 'events/{slug}'
  6fd1ed84-e519-4c3e-9ca0-003fc29b2a22:
    enabledByDefault: true
    hasUrls: true
    template: _elements/event
    uriFormat: 'events/{slug}'
  af84148e-1f0d-43e7-ab24-26c4d193c209:
    enabledByDefault: true
    hasUrls: true
    template: _elements/event
    uriFormat: 'events/{slug}'
type: channel
```

```yaml
actor: Tester
paths:
  tests: tests
  log: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
bootstrap: _bootstrap.php
modules:
  config:
    \craft\test\Craft:
      configFile: "tests/_craft/config/test.php"
      entryUrl: "http://client.test/index.php"
      projectConfig: { folder: 'config/project', reset: false }
      migrations: []
      plugins: []
      cleanup: true
      transaction: true
      dbSetup: { clean: true, setupCraft: true, applyMigrations: true }

```

Any other helpful info I can provide? Thanks!

### Steps to reproduce

1. Run sample test referencing something in the project config
2. See error

### Additional info

- Craft version: Craft Pro 3.5.11.1
- PHP version: 7.3.16
- Database driver & version: MySQL 5.7.29
