### ISSUE TITLE
Debug Bar Logo affected from frontend styles

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#7073]
### Description
In the debug bar the craft logo on the left side is affected from my frontend styles.
Maybe you can put in a bit CSS for width and height :)

```css
img {
  max-width: 100%;
  height: auto;
  font-style: italic;
  vertical-align: middle;
  outline: none;
  width: 100%;
}
```

![image](https://user-images.githubusercontent.com/764292/97602918-2fdeea80-1a0c-11eb-9ceb-31c08a9d6b26.png)
