### ISSUE TITLE
[Testing] Project config syncing extra site when running test suite

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#7412]
### Description
I'm noticing when running my test suite that multiple records are being added to the `sites` table. I'd suspect that it's happening when Craft is installed and then syncing project config data; it's adding a new record instead of updating or replacing the existing record?

![image](https://user-images.githubusercontent.com/199985/105503221-52dc0c00-5c94-11eb-9123-8021284dc8f1.png)

Because here is what i have in my project config (and this is the only site entry in project config):

![image](https://user-images.githubusercontent.com/199985/105503324-6edfad80-5c94-11eb-9329-954e9c352344.png)

```yaml
actor: Tester
paths:
  tests: tests
  log: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
bootstrap: _bootstrap.php
modules:
  config:
    \craft\test\Craft:
      configFile: "tests/_craft/config/test.php"
      entryUrl: "http://client.test/index.php"
      projectConfig: { folder: 'config/project', reset: false }
      migrations: []
      plugins: [
        {
          class: '\craft\commerce\Plugin',
          handle: 'commerce'
        }
      ]
      cleanup: true
      transaction: true
      dbSetup: { clean: true, setupCraft: true }
```

This sort of again hits on a problem I was having here: https://github.com/craftcms/commerce/issues/1953

And the resolution was basically, use fixtures. Which is ok, but it's pretty duplicative to have to create fixtures for all of the settings data that project config is supposed to handle. I guess I'm just hoping for a little more clarity on what we should expect out of project config syncing in the test suite. Is the expectation that it syncs the project config from the site exacly the same? If not, that makes automated testing a bit more challenging.

### Steps to reproduce

1. Setup test suite with `codeception.yml` file (above)
2. Run a super simple hello world test
3. See that DB contains 2 records in the `sites` table
4. (Bonus: also see that DB does not contain any Commerce settings from project config)

### Additional info

- Craft version: Craft Pro 3.5.18
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.29
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Command Palette</th>
                        <td>3.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Craft Commerce</th>
                        <td>3.2.14</td>
                    </tr>
                                    <tr>
                        <th class="light">Ray</th>
                        <td>1.0.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.8.5</td>
                    </tr>
                                    <tr>
                        <th class="light">Scout</th>
                        <td>2.3.1</td>
                    </tr>
                            </tbody>
        </table>
