### ISSUE TITLE
[FR] Add human-readable handles as comments to project config

### ISSUE THREAD

**Issue by FreekVR** [craftcms/cms#7584]
### Description
Hi! We've been using the project config feature for a while now, and with the changes to split out config to separated files we're seeing a lot of improvements in merge conflict resolutions etc.

However, as we work with multiple developers on a single project, sometimes someone will check out an upstream branch, and forget to properly apply all the upstream project config changes, or just flat-out rebuild the config from a divergent local DB before applying the newer changes.

Anyway, sometimes this leads to some mishaps in fields disappearing from entry types where they were just added for example. We use code reviews via pull requests, but it's really hard to read the associations between different entities.

A good example would be a diff for this entry type config file for example:

![image](https://user-images.githubusercontent.com/417416/108182831-baf20680-7109-11eb-9ec3-1937bf03557f.png)

I can't really see what's been added / changes here unless I manually go into the config/fields folder and check for the UUID.

A simple change which would be REALLY helpful would be to add a YAML comment wheever a UUID is referenced for another config file.

For example;

```yaml
fieldLayouts:
  a10f84d1-1f05-4616-9de0-c5e35e7be121:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: Bedrijfsnaam
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 74c655a8-9bd5-41db-9402-f58841eed0ff # descriptionField
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
```

Would perhaps also be helpful for other areas:

Graphql scopes
```yaml
isPublic: false
name: Frontend
scope:
  - 'sections.b24278b3-77ef-490f-8d5e-10d2dc43a481:read' # sections.article.read
```

Section site settings
```yaml
siteSettings:
  0aedc5e6-b00f-4a0c-816a-fd98100cf2da: # myPrimarySiteEN
```

I'm probably missing a few areas here but you get the idea :)
