### ISSUE TITLE
Duplicate entries created in tests when calling saveElement once.

### ISSUE THREAD

**Issue by myleshyson** [craftcms/cms#7616]
### Description
I'm noticing that when creating an entry in a test, that entry is saved to the database twice. Here's the test I'm running.
```php
<?php

namespace tests\integration;

use Codeception\Test\Unit;
use craft\elements\Entry;
use tests\fixtures\LocationFixture;
use tests\fixtures\ProviderFixture;

class GmbModuleTest extends Unit
{
    /**
     * @var \UnitTester
     */
    protected $tester;

    public function testCreatedLocationTriggersQueue()
    {
        $section = \Craft::$app->getSections()->getSectionByHandle('locations');
        $location = new Entry();
        $location->sectionId = $section->id;
        $location->title = 'Some New Location';
        $location->typeId = $section->getEntryTypes()[0]->id;
        $location->enabled = true;
        \Craft::$app->getElements()->saveElement($location);
    }
}

```

```yaml
actor: Tester
paths:
  tests: tests
  log: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
bootstrap: _bootstrap.php
params:
  - tests/.env
modules:
  config:
    \craft\test\Craft:
      configFile: "tests/_craft/config/test.php"
      entryUrl: "http://host.docker.internal/index.php"
      projectConfig: {
        folder: "config/project",
        reset: false
      }
      migrations: []
      plugins: []
      cleanup: true
      transaction: true
      dbSetup: { clean: true, setupCraft: true }
```

```yaml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests.

actor: UnitTester
modules:
    enabled:
        - \craft\test\Craft
        - Asserts
        - \Helper\Unit

```

```shell
docker-compose exec php ./vendor/bin/codecept run integration
```

![Screen Shot 2021-02-24 at 4 47 41 PM](https://user-images.githubusercontent.com/11747187/109070045-05522500-76c0-11eb-87dd-c342299b15e0.png)

### Steps to reproduce

1.  Create an entry in a test using `saveElement`
2. See two separate entries created from that one operation.

### Additional info

- Craft version: 3.6.7
- PHP version: 7.4.14
- Database driver & version: MySQL 8.0.23
- Plugins & versions:
