### ISSUE TITLE
Returning `true` from`useFieldset()` for custom plugins has resizing issues

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#9734]
### Description

If you follow the [Field Type Accessibility](https://craftcms.com/knowledge-base/upgrading-to-craft-3-6#field-type-accessibility) instructions and have your custom field type return `true` from the new `useFieldset()`, visual errors occur. See movie:

https://user-images.githubusercontent.com/7570798/129764368-6723bf96-b5d6-4de2-ba95-0984d77a7488.mov

Changing it back to have it return `false` causes the errors to go away.

It appears that some JavaScript somewhere is attempting to resize things and is confused by the `<fieldset>` wrapper. I've checked my own JavaScript code, and am not seeing anything that looks like it could be causing it.

Interestingly, just putting `<fieldset>` wrappers in my field twig code causes similar "ever expanding" text fields in the resulting CP layout.

### Steps to reproduce

1. Have an entry with an SEO Settings field in it
2. Resize the window

### Additional info

- Craft version: 3.7.8
- PHP version: 8.x
- Database driver & version: n/a
- Plugins & versions: SEOmatic 3.3.48

**Comment by brandonkelly** [comment]
I’m not able to reproduce this locally (tried with a couple field types including SEO Settings). Nothing in the JS is setting the field/fieldset widths. Guessing there is some content inside the field that is forcing its width, though I’m not sure what that would be. Try going through the inner elements setting `display: none` to isolate it.

**Comment by khalwat** [comment]
Found it -- it's a third party JS that implements the tag fields in the SEO Keywords field. My guess is you didn't have that field enabled, and thus didn't see it happen.

Investigating what it's doing now...

**Comment by khalwat** [comment]
So this is actually pretty interesting. The element `<fieldset>` comes with these built-in styles for Chrome:

```css
fieldset {
    display: block;
    margin-inline-start: 2px;
    margin-inline-end: 2px;
    padding-block-start: 0.35em;
    padding-inline-start: 0.75em;
    padding-inline-end: 0.75em;
    padding-block-end: 0.625em;
    min-inline-size: min-content;
    border-width: 2px;
    border-style: groove;
    border-color: threedface;
    border-image: initial;
}
```

Whereas `<div>` just has:

```css
block {
    display: block;
}
```

So _apparently_ [min-inline-size](https://developer.mozilla.org/en-US/docs/Web/CSS/min-inline-size) "defines the horizontal or vertical minimal size of an element's block, depending on its writing mode."

This must somehow throw off the bounding rectangle calculations in the above third party JS, because adding:

```css
fieldset {
    min-inline-size: initial;
}
```

...fixes everything.
